-- GRAVITY STRIKE v0.9
-- language configuration file
-- english, german, croatian


-- set menu strings, english language

if ( LANGUAGE == LANG_EN ) then

-- main menu
set_string( MENU_SINGLEPLAYER,            "Single Player" )
set_string( MENU_SPLITSCREEN,             "Two Player Match" )
set_string( MENU_MINIGAME,                "Mini Game" )
set_string( MENU_NETGAME,                 "Network Game" )
set_string( MENU_OPTIONS,                 "Options" )
set_string( MENU_CREDITS,                 "Credits" )
set_string( MENU_SHIPBUILDER,             "Ship Builder" )
set_string( MENU_BACK,                    "Back" )
set_string( MENU_QUIT,                    "Quit" )

-- options menu
set_string( MENU_CAP_OPTIONS,             "Game Options" )
set_string( MENU_LANGUAGE,                "Language" )
set_string( MENU_LANG_EN,                 "English" )
set_string( MENU_LANG_DE,                 "German" )
set_string( MENU_LANG_CR,                 "Croatian" )
set_string( MENU_PIXAMOUNT,               "Pixel Effects" )
set_string( MENU_VOLUME,                  "Effects Volume" )
set_string( MENU_MVOLUME,                 "Music Volume" )
set_string( MENU_CONTROLS,                "Set Controls" )
set_string( MENU_2PCONTROLS,              "Set 2P Controls" )
set_string( MENU_SPCONTROLS,              "Set Sp. Controls" )
set_string( MENU_RESOLUTION,	          "Resolution" )

-- ship builder (choose ship)
set_string( MENU_CAP_CHOOSESHIP,          "Choose Ship" )
set_string( MENU_NEWSHIP,                 "New Ship" )
set_string( MENU_NEXTPAGE,                "Next Page" )
set_string( MENU_LASTPAGE,                "Last Page" )

-- ship builder
set_string( MENU_CAP_SHIPBUILDER,         "Ship Builder" )
set_string( MENU_MSG_SHIPLOADERROR,       "Error loading ship!" )
set_string( MENU_MSG_REALLYDELETE,        "Really delete this ship?" )
set_string( MENU_EDITWEAPONS,             "Edit Weapons" )
set_string( MENU_EDITSHIP,                "Edit Ship" )
set_string( MENU_SAVE,                    "Save" )
set_string( MENU_SAVENEW,                 "Save as New" )
set_string( MENU_DELETE,                  "Delete" )
set_string( MENU_SHIP_NAME,               "Name" )
set_string( MENU_SHIP_DESC,               "Description" )
set_string( MENU_SHIP_LOADIMAGE,          "Import Image" )
set_string( MENU_SHIP_LOADIMAGE_FS,       "Load Image (BMP, PCX, TGA)" )
set_string( MENU_SHIP_REMPOINTS,          "Energy left" )
set_string( MENU_SHIP_HULL,               "Hull" )
set_string( MENU_SHIP_SHIELD,             "Shields" )
set_string( MENU_SHIP_HULL_RE,            "Hull Repair" )
set_string( MENU_SHIP_SHIELD_RE,          "Shield Recharge" )
set_string( MENU_SHIP_WEAPON_RE,          "Weapon Recharge" )
set_string( MENU_SHIP_WALLSHIELD,         "Wall Shields" )
set_string( MENU_SHIP_RADAR_ZOOM,         "Max Radar Zoom" )
set_string( MENU_SHIP_WEAPON_SLOTS,       "Weapon Slots" )
set_string( MENU_SHIP_TURN_SPEED,         "Turn Speed" )
set_string( MENU_SHIP_MAX_SPEED,          "Maximum Speed" )
set_string( MENU_SHIP_ACCELERATION,       "Acceleration" )
set_string( MENU_SHIP_FUEL_CONSUMPTION,   "Fuel Consumption" )
set_string( MENU_SHIP_WEAPON_STORAGE,     "Weapon Storage" )
set_string( MENU_SHIP_EXTRA,              "Extras" )
set_string( MENU_SHIP_AFTERBURNER,        "Afterburner" )
set_string( MENU_SHIP_DEFLECTOR,          "Deflector" )
set_string( MENU_SHIP_CLOAK,              "Cloaking Mode" )
set_string( MENU_SHIP_WEAPONS,            "Weapons" )
set_string( MENU_SHIP_TEXT_WEAPAVAIL,     "Available Weapons" )
set_string( MENU_SHIP_TEXT_WEAPSLOTS,     "Weapon Slots" )
set_string( MENU_SHIP_TEXT_WEAPDESC,      "Description" )
set_string( MENU_SHIP_W_SBLASTER,         "Single Blaster" )
set_string( MENU_SHIP_W_DBLASTER,         "Double Blaster" )
set_string( MENU_SHIP_W_BOMB,             "Bomb" )
set_string( MENU_SHIP_W_BIGBOMB,          "Bigbomb" )
set_string( MENU_SHIP_W_ROCKETS,          "Rockets" )
set_string( MENU_SHIP_W_MINES,            "Mines" )
set_string( MENU_SHIP_W_FREEZER,          "Freezer" )
set_string( MENU_SHIP_W_SHRINKER,         "Shrinker" )
set_string( MENU_SHIP_W_PROBE,            "Probe" )
set_string( MENU_SHIP_W_GAS,              "Delirium Bomb" )
set_string( MENU_SHIP_W_LASER,            "Laser" )
set_string( MENU_SHIP_W_BUMPER,           "Bumper Bomb" )
set_string( MENU_SHIP_W_SHOTGUN,          "Shotgun" )
set_string( MENU_SHIP_W_ACID,             "Acid" )
set_string( MENU_SHIP_WI_SBLASTER,        "Single Blaster#1#1#1#The Single Blaster is the standard weapon of all ships. It's not very strong, but the bullets are accurate and fast." )
set_string( MENU_SHIP_WI_DBLASTER,        "Double Blaster#2#1#2#The Double Blaster combines the speed and accuracy of the Single Blaster with a better damage factor." )
set_string( MENU_SHIP_WI_BOMB,            "Bomb#2#2#2#The Bomb explodes into eight bullets spreading in eight directions." )
set_string( MENU_SHIP_WI_BIGBOMB,         "Bigbomb#25#15#20#The Bigbomb just drops out of your weapon slot moving in the direction of gravity. It's the strongest weapon." )
set_string( MENU_SHIP_WI_ROCKETS,         "Rocket#6#6#3#Rockets automatically head into the direction of the nearest target." )
set_string( MENU_SHIP_WI_MINES,           "Mine#15 (max)#15 (max)#10 (max)#Mines are invisible, stationery weapons exploding when an enemy gets into activation radius. Their explosion damage depends on distance." )
set_string( MENU_SHIP_WI_FREEZER,         "Freezer#0#0#0#When the Freezer hits a player, he is unable to move for 6 seconds. Enough time to shoot him." )
set_string( MENU_SHIP_WI_SHRINKER,        "Shrinker#0#0#0#The Shrinker shrinks enemy players to a tiny toy ship (20 seconds). Shrinked players can't shoot and you can just fly against them to kill them." )
set_string( MENU_SHIP_WI_PROBE,           "Probe#1 (10)#1 (6)#1 (10)#The Probe, placed near your enemy, follows and shoots him for 10 seconds." )
set_string( MENU_SHIP_WI_GAS,             "Delirium Bomb#0#0#0#The Delirium Bomb explodes after 2 seconds. Then every enemy player flying through the gas will suffer from some delirium effects. Very good to cut off chasing enemies." )
set_string( MENU_SHIP_WI_LASER,           "Laser#2#3#0#The laser with its fast shots is great for weakening shields. But beware: It is not effective against the hull." )
set_string( MENU_SHIP_WI_BUMPER,          "Bumper Bomb#0#0#0#When the Bumper Bomb hits another player, his ship accelerates in the bomb's direction. This bomb only affects wall shields." )
set_string( MENU_SHIP_WI_SHOTGUN,         "Shotgun#1#0#1#The Shotgun is the ideal defensive weapon. It takes out most rockets and probes, but it is only effective against the hull.")
set_string( MENU_SHIP_WI_ACID,            "Acid#1#0#1#The Acid penetrates shields (design leak) and affects the integrity of the hull." )
set_string( MENU_SHIP_SLOT1,              "Slot 1" )
set_string( MENU_SHIP_SLOT2,              "Slot 2" )
set_string( MENU_SHIP_SLOT3,              "Slot 3" )
set_string( MENU_SHIP_SLOT4,              "Slot 4" )
set_string( MENU_SHIP_SLOT5,              "Slot 5" )
set_string( MENU_SHIP_SLOT6,              "Slot 6" )
set_string( MENU_SHIP_DAMAGE_SP,          "Singleplayer" )
set_string( MENU_SHIP_DAMAGE_MP,          "Damage" )

-- single player
set_string( MENU_CAP_SINGLEPLAYER,        "Single Player Mission" )
set_string( MENU_CAP_MINIGAME,            "Mini Game" )
set_string( MENU_DISP_RACES,              "Races" )
set_string( MENU_DISP_MISSIONS,           "Missions" )
set_string( MENU_DISP_DOGFIGHTS,          "Dogfights" )
set_string( MENU_CAP_AUTHOR,              "Level Author" )
set_string( MENU_LEVEL_LOCKED,            "This level is locked" )

-- twoplayer dogfight
set_string( MENU_CAP_SPLITSCREEN,         "Splitscreen Match" )
set_string( MENU_PLAY,                    "Fight!" )
set_string( MENU_PLAY_MINIGAME,           "Play!" )
set_string( MENU_NAME_P1,                 "Name Player 1" )
set_string( MENU_NAME_P2,                 "Name Player 2" )
set_string( MENU_2P_CHOOSESHIP,           "Choose Ship" )
set_string( MENU_2P_EDITSHIP,             "Edit Ship" )
set_string( MENU_GRAVITY,                 "Gravity Level" )
set_string( MENU_MAXFRAGS,                "Max Frags" )
set_string( MENU_MAXTIME,                 "Max Time" )
set_string( MENU_EXTRAS,                  "Extras" )
set_string( MENU_ONESCREEN_MAP,           "Onescreen-Map" )
set_string( MENU_SCRIPTING,               "Ingame Scripting" )
set_string( MENU_LEVELEXTRA,              "Activate Extra" )
set_string( MENU_CAPTURE_THE_FLAG,        "Capture the Flag" )
set_string( MENU_HUNTER_HUNTED,           "Hunter-Hunted" )
set_string( MENU_LAPS,                    "Laps" )
set_string( MENU_COMPUTER_PLAYER,         "Player 2 = Computer" )
set_string( MENU_COMPUTER_PLAYER_STRENGTH, "Strength" )
set_string( MENU_2NDPLAYER,               "2 Players" )
set_string( MENU_LEVELINFO,               "Level info" )
set_string( MENU_HANDICAP,                "Handicap / Fairplay Mode" )

-- network game
set_string( MENU_CAP_NETGAME,             "Network Match" )
set_string( MENU_CAP_NETGAME_SERVER,      "Network Match - Server" )
set_string( MENU_CAP_NETGAME_CLIENT,      "Network Match - Client" )
set_string( MENU_SERVER,                  "Create new Game (Server)" )
set_string( MENU_CLIENT,                  "Join Game (Client)" )
set_string( MENU_READY,                   "ready" )
set_string( MENU_I_AM_READY,              "Ok, I'm ready" )
set_string( MENU_LEVEL_NOT_AVAILABLE,     "Level not available!" )

-- ingame
set_string( GAME_EXTRA,                   "Extra" )
set_string( GAME_AMMOPACK,                "Ammo Pack" )
set_string( GAME_TIME,                    "Time" )
set_string( GAME_TIMEREM,                 "Remaining Time" )
set_string( GAME_CARGO,                   "Cargo" )
set_string( GAME_MAN,                     "A Man" )
set_string( GAME_SOMETHING,               "Something..." )
set_string( GAME_WEIGHT,                  "Weight" )
set_string( GAME_CARGOREC,                "Cargo Received" )
set_string( GAME_HOMEBASE,                "Homebase" )
set_string( GAME_PANEL_FUEL,              "FUEL" )
set_string( GAME_PANEL_EXTRA,             "EXTRA" )
set_string( GAME_PANEL_FRAGS,             "FRAGS" )
set_string( GAME_PANEL_SHIPS,             "SHIPS" )
set_string( GAME_MISSION_DONE,            "MISSION DONE!" )
set_string( GAME_MISSION_FAILED,          "MISSION FAILED..." )
set_string( GAME_YOU_ARE_DEAD,            "YOU ARE DEAD." )
set_string( GAME_EXTRA_UPGRADE,           "Weapon Upgrade" )
set_string( GAME_EXTRA_FUEL,              "Fuel" )
set_string( GAME_EXTRA_FULLSHIELD,        "Full Shield/Hull" )
set_string( GAME_EXTRA_FULLWSHIELD,       "Full Wall Shield" )
set_string( GAME_EXTRA_INVULNERABILITY,   "Indestructibility" )
set_string( GAME_DAMAGE,                  "DAMAGE" )
set_string( GAME_DAMAGE_THRUSTER,         "Thrusters" )
set_string( GAME_DAMAGE_STEERING,         "Steering" )
set_string( GAME_DAMAGE_FUEL,             "Fuel Leak" )
set_string( GAME_DAMAGE_WEAPONS,          "Weapon system" )
set_string( GAME_DAMAGE_SHIELD,           "Shield system" )
set_string( GAME_DAMAGE_LANDING,          "Landing Stabilizers" )
set_string( GAME_DAMAGE_RADAR,            "Radar System" )
set_string( GAME_ESC_EXIT,		  "Exit Level" )
set_string( GAME_ESC_RESTART,	          "Restart Level" )
set_string( GAME_ESC_OTHER_KEY,           "Other" )
set_string( GAME_ESC_CONTINUE,            "Continue" )

-- statistics screen
set_string( STATS_CAP_1PLAYER,            "Mission Statistics" )
set_string( STATS_CAP_2PLAYER,            "2 Player Statistics" )
set_string( STATS_CAP_NETWORK,            "Netgame Statistics" )
set_string( STATS_MODE,                   "Game Mode" )
set_string( STATS_MODE_DOGFIGHT,          "Dogfight" )
set_string( STATS_MODE_RACE,              "Race" )
set_string( STATS_PLAYER,                 "Player" )
set_string( STATS_HITPERCENT,             "Hit Percent" )
set_string( STATS_FRAGS,                  "Frags" )
set_string( STATS_SUICIDES,               "Suicides" )
set_string( STATS_EXTRASTAKEN,            "Extras taken" )
set_string( STATS_WINNER,                 "Winner" )
set_string( STATS_DRAW,                   "Draw" )
set_string( STATS_PLACE,                  "Place" )
set_string( STATS_SCORE,                  "Score" )
set_string( STATS_LAP,                    "Lap" )
set_string( STATS_TIME,                   "Time" )
set_string( STATS_OVERALL_TIME,           "Overall Time" )
set_string( STATS_TIMEPLAYED,             "Time played" )
set_string( STATS_BONUS,                  "Bonus points" )
set_string( STATS_ENEMY_BONUS,            "Enemy Bonus" )
set_string( STATS_LOSTLIFES,              "Lost Ships" )
set_string( STATS_MISSION_STATUS,         "Mission status" )
set_string( STATS_COMPLETED,              "completed" )
set_string( STATS_FAILED,                 "failed" )
set_string( STATS_HISCORE_NEW,            "Gratulations, you bet your last highscore!" )
set_string( STATS_HISCORE_OLD,            "Sorry, you didn't bet your last score..." )
set_string( STATS_HISCORE_DISABLED,       "Highscores disabled" )

-- controls
set_string( MENU_CAP_CONTROLS,            "Player Controls" )
set_string( MENU_CAP_2PCONTROLS,          "2 Player Controls" )
set_string( MENU_CAP_SPCONTROLS,          "Special Controls" )
set_string( MENU_TEXT_PLAYER1,            "First Player" )
set_string( MENU_TEXT_PLAYER2,            "Second Player" )
set_string( CONTROL_LEFT,                 "Turn left" )
set_string( CONTROL_RIGHT,                "Turn right" )
set_string( CONTROL_THRUST,               "Thrusters" )
set_string( CONTROL_SHOOT,                "Shoot" )
set_string( CONTROL_NEXTWEAP,             "Next Weapon" )
set_string( CONTROL_PREVWEAP,             "Previous Weapon" )
set_string( CONTROL_W1,                   "Weapon 1" )
set_string( CONTROL_W2,                   "Weapon 2" )
set_string( CONTROL_W3,                   "Weapon 3" )
set_string( CONTROL_W4,                   "Weapon 4" )
set_string( CONTROL_W5,                   "Weapon 5" )
set_string( CONTROL_W6,                   "Weapon 6" )
set_string( CONTROL_EXTRA_ACTION,         "Extra Action" )
set_string( CONTROL_EXTRA2,               "Special" )
set_string( CONTROL_PAUSE,	              "Pause" )
set_string( CONTROL_SCREENSHOT,           "Screenshot" )
set_string( CONTROL_PANEL,                "Panel on/off" )
set_string( CONTROL_DEBUG,                "Debug messages" )
set_string( CONTROL_CHAT,                 "Chat" )

-- keyboard
set_string( KEY_LCONTROL,                 "Control Left" )
set_string( KEY_RCONTROL,                 "Control Right" )
set_string( KEY_ALT,                      "Alt Left" )
set_string( KEY_ALTGR,                    "Alt Gr" )
set_string( KEY_LSHIFT,                   "Shift Left" )
set_string( KEY_RSHIFT,                   "Shift Right" )
set_string( KEY_SPACE,                    "Space" )
set_string( KEY_LWIN,                     "Left Win" )
set_string( KEY_RWIN,                     "Right Win" )
set_string( KEY_MENU,                     "Win Menu" )
set_string( KEY_TAB,                      "TAB" )
set_string( KEY_ENTER,                    "Enter" )
set_string( KEY_BACKSPACE,                "Backspace" )
set_string( KEY_MINUS,                    "Minus" )
set_string( KEY_ESC,                      "Escape" )
set_string( KEY_TILDE,                    "Tilde ~")
set_string( KEY_EQUALS,                   "Equal Sign =" )
set_string( KEY_OPENBRACE,                "Open Brace" )
set_string( KEY_CLOSEBRACE,               "Close Brace" )
set_string( KEY_COLON,                    "Colon" )
set_string( KEY_QUOTE,                    "Quote" )
set_string( KEY_BACKSLASH,                "Backslash" )
set_string( KEY_BACKSLASH2,               "Backslash 2" )
set_string( KEY_COMMA,                    "Comma" )
set_string( KEY_STOP,                     "Stop" )
set_string( KEY_SLASH,                    "Slash" )
set_string( KEY_NUMLOCK,                  "Num Lock" )
set_string( KEY_CAPSLOCK,                 "Capslock" )
set_string( KEY_SCRLOCK,                  "Scroll Lock" )
set_string( KEY_F1,                       "F1" )
set_string( KEY_F2,                       "F2" )
set_string( KEY_F3,                       "F3" )
set_string( KEY_F4,                       "F4" )
set_string( KEY_F5,                       "F5" )
set_string( KEY_F6,                       "F6" )
set_string( KEY_F7,                       "F7" )
set_string( KEY_F8,                       "F8" )
set_string( KEY_F9,                       "F9" )
set_string( KEY_F10,                      "F10" )
set_string( KEY_F11,                      "F11" )
set_string( KEY_F12,                      "F12" )
set_string( KEY_PRTSCR,                   "Print Screen" )
set_string( KEY_PAUSE,                    "Pause" )
set_string( KEY_INSERT,                   "Insert" )
set_string( KEY_DEL,                      "Delete" )
set_string( KEY_HOME,                     "Home" )
set_string( KEY_END,                      "End" )
set_string( KEY_PGUP,                     "Page Up" )
set_string( KEY_PGDN,                     "Page Down" )
set_string( KEY_LEFT,                     "Arrow Left" )
set_string( KEY_RIGHT,                    "Arrow Right" )
set_string( KEY_UP,                       "Arrow Up" )
set_string( KEY_DOWN,                     "Arrow Down" )
set_string( KEY_SLASH_PAD,                "Slash [Pad]" )
set_string( KEY_0_PAD,                    "0 [Pad]" )
set_string( KEY_1_PAD,                    "1 [Pad]" )
set_string( KEY_2_PAD,                    "2 [Pad]" )
set_string( KEY_3_PAD,                    "3 [Pad]" )
set_string( KEY_4_PAD,                    "4 [Pad]" )
set_string( KEY_5_PAD,                    "5 [Pad]" )
set_string( KEY_6_PAD,                    "6 [Pad]" )
set_string( KEY_7_PAD,                    "7 [Pad]" )
set_string( KEY_8_PAD,                    "8 [Pad]" )
set_string( KEY_9_PAD,                    "9 [Pad]" )
set_string( KEY_ENTER_PAD,                "Enter [Pad]" )
set_string( KEY_PLUS_PAD,                 "Plus [Pad]" )
set_string( KEY_MINUS_PAD,                "Minus [Pad]" )
set_string( KEY_ASTERISK,                 "Asterisk" )
set_string( JOY0_UP,                      "Joy 1: Up" )
set_string( JOY0_DOWN,                    "Joy 1: Down" )
set_string( JOY0_LEFT,                    "Joy 1: Left" )
set_string( JOY0_RIGHT,                   "Joy 1: Right" )
set_string( JOY0_B1,                      "Joy 1: Button 1" )
set_string( JOY0_B2,                      "Joy 1: Button 2" )
set_string( JOY0_B3,                      "Joy 1: Button 3" )
set_string( JOY0_B4,                      "Joy 1: Button 4" )
set_string( JOY0_B5,                      "Joy 1: Button 5" )
set_string( JOY0_B6,                      "Joy 1: Button 6" )
set_string( JOY1_UP,                      "Joy 2: Up" )
set_string( JOY1_DOWN,                    "Joy 2: Down" )
set_string( JOY1_LEFT,                    "Joy 2: Left" )
set_string( JOY1_RIGHT,                   "Joy 2: Right" )
set_string( JOY1_B1,                      "Joy 2: Button 1" )
set_string( JOY1_B2,                      "Joy 2: Button 2" )
set_string( JOY1_B3,                      "Joy 2: Button 3" )
set_string( JOY1_B4,                      "Joy 2: Button 4" )
set_string( JOY1_B5,                      "Joy 2: Button 5" )
set_string( JOY1_B6,                      "Joy 2: Button 6" )

-- other/misc
set_string( MENU_YES,                     "Yes" )
set_string( MENU_NO,                      "No" )
set_string( MENU_OK,                      "Okay" )

-- ===========================================================

-- GERMAN language

elseif ( LANGUAGE == LANG_DE ) then

-- main menu
set_string( MENU_SINGLEPLAYER,            "Ein Spieler" )
set_string( MENU_SPLITSCREEN,             "Zwei Spieler" )
set_string( MENU_MINIGAME,                "Minispiel" )
set_string( MENU_NETGAME,                 "Netzwerkspiel" )
set_string( MENU_OPTIONS,                 "Optionen" )
set_string( MENU_CREDITS,                 "Credits" )
set_string( MENU_SHIPBUILDER,             "Schiffseditor" )
set_string( MENU_BACK,                    "Zurueck" )
set_string( MENU_QUIT,                    "Ende" )

-- options menu
set_string( MENU_CAP_OPTIONS,             "Spieloptionen" )
set_string( MENU_LANGUAGE,                "Sprache" )
set_string( MENU_LANG_EN,                 "Englisch" )
set_string( MENU_LANG_DE,                 "Deutsch" )
set_string( MENU_LANG_CR,                 "Kroatisch" )
set_string( MENU_PIXAMOUNT,               "Pixeleffekte" )
set_string( MENU_VOLUME,                  "Effekt-Lautst." )
set_string( MENU_MVOLUME,                 "Musik-Lautst." )
set_string( MENU_CONTROLS,                "Steuerung" )
set_string( MENU_2PCONTROLS,              "2-Sp.-Steuerung" )
set_string( MENU_SPCONTROLS,              "Spezialtasten" )
set_string( MENU_RESOLUTION,	          "Aufloesung" )

-- ship builder (choose ship)
set_string( MENU_CAP_CHOOSESHIP,          "Schiff waehlen" )
set_string( MENU_NEWSHIP,                 "Neu!" )
set_string( MENU_NEXTPAGE,                "Seite vor" )
set_string( MENU_LASTPAGE,                "Seite zurueck" )

-- ship builder
set_string( MENU_CAP_SHIPBUILDER,         "Schiffseditor" )
set_string( MENU_MSG_SHIPLOADERROR,       "Fehler beim Laden!" )
set_string( MENU_MSG_REALLYDELETE,        "Dieses Schiff wirklich loeschen?" )
set_string( MENU_EDITWEAPONS,             "Waffen" )
set_string( MENU_EDITSHIP,                "Schiff" )
set_string( MENU_SAVE,                    "Speichern" )
set_string( MENU_SAVENEW,                 "Als Neu sp." )
set_string( MENU_DELETE,                  "Loeschen" )
set_string( MENU_SHIP_NAME,               "Name" )
set_string( MENU_SHIP_DESC,               "Beschreibung" )
set_string( MENU_SHIP_LOADIMAGE,          "Bild importieren" )
set_string( MENU_SHIP_LOADIMAGE_FS,       "Bild laden (BMP, PCX, TGA)" )
set_string( MENU_SHIP_REMPOINTS,          "Uebrige Energie" )
set_string( MENU_SHIP_HULL,               "Huelle" )
set_string( MENU_SHIP_SHIELD,             "Schilde" )
set_string( MENU_SHIP_HULL_RE,            "Huellen-Reparatur" )
set_string( MENU_SHIP_SHIELD_RE,          "Schild-Aufladung" )
set_string( MENU_SHIP_WEAPON_RE,          "Waffen-Aufladung" )
set_string( MENU_SHIP_WALLSHIELD,         "Abprallschilde" )
set_string( MENU_SHIP_RADAR_ZOOM,         "Max. Radar-Zoom" )
set_string( MENU_SHIP_WEAPON_SLOTS,       "Waffenschaechte" )
set_string( MENU_SHIP_TURN_SPEED,         "Drehgeschwindigkeit" )
set_string( MENU_SHIP_MAX_SPEED,          "Max. Geschwindigkeit" )
set_string( MENU_SHIP_ACCELERATION,       "Beschleunigung" )
set_string( MENU_SHIP_FUEL_CONSUMPTION,   "Treibstoffverbrauch" )
set_string( MENU_SHIP_WEAPON_STORAGE,     "Waffenkapazitaet" )
set_string( MENU_SHIP_EXTRA,              "Extras" )
set_string( MENU_SHIP_AFTERBURNER,        "Nachbrenner" )
set_string( MENU_SHIP_DEFLECTOR,          "Deflektor" )
set_string( MENU_SHIP_CLOAK,              "Tarnmodus" )
set_string( MENU_SHIP_WEAPONS,            "Waffen" )
set_string( MENU_SHIP_TEXT_WEAPAVAIL,     "Verfuegbare Waffen" )
set_string( MENU_SHIP_TEXT_WEAPSLOTS,     "Waffenschaechte" )
set_string( MENU_SHIP_TEXT_WEAPDESC,      "Beschreibung" )
set_string( MENU_SHIP_W_SBLASTER,         "Single Blaster" )
set_string( MENU_SHIP_W_DBLASTER,         "Double Blaster" )
set_string( MENU_SHIP_W_BOMB,             "Bombe" )
set_string( MENU_SHIP_W_BIGBOMB,          "Bigbomb" )
set_string( MENU_SHIP_W_ROCKETS,          "Raketen" )
set_string( MENU_SHIP_W_MINES,            "Minen" )
set_string( MENU_SHIP_W_FREEZER,          "Freezer" )
set_string( MENU_SHIP_W_SHRINKER,         "Shrinker" )
set_string( MENU_SHIP_W_PROBE,            "Sonde" )
set_string( MENU_SHIP_W_GAS,              "Delirium-Bombe" )
set_string( MENU_SHIP_W_LASER,            "Laser" )
set_string( MENU_SHIP_W_BUMPER,           "Bumper-Bombe" )
set_string( MENU_SHIP_W_SHOTGUN,          "Schrotflinte" )
set_string( MENU_SHIP_W_ACID,             "Saeure" )
set_string( MENU_SHIP_WI_SBLASTER,        "Single Blaster#1#1#1#Der Single Blaster ist die Standardwaffe mit unendlich Munition." )
set_string( MENU_SHIP_WI_DBLASTER,        "Double Blaster#2#1#2#Der Double Blaster verschiesst zwei schnelle Projektile, jeweils doppelt so stark wie die des Single Blasters." )
set_string( MENU_SHIP_WI_BOMB,            "Bombe#2#2#2#Die Bombe explodiert beim Auftreffen in acht normale Projektile, die sich in 8 Richtungen bewegen." )
set_string( MENU_SHIP_WI_BIGBOMB,         "Bigbomb#25#15#20#Die Bigbomb loest sich aus dem Waffenschacht und faellt in Richtung der Gravitation. Staerkste Waffe." )
set_string( MENU_SHIP_WI_ROCKETS,         "Rakete#6#6#3#Raketen fliegen automatisch in Richtung des naechsten Gegners." )
set_string( MENU_SHIP_WI_MINES,           "Mine#15 (max)#15 (max)#10 (max)#Minen sind unsichtbare, stationaere Waffen, die explodieren, wenn ein Gegner ihren Aktivitaetsradius ueberschreitet. Der Schaden ist abhaengig von der Entfernung." )
set_string( MENU_SHIP_WI_FREEZER,         "Freezer#0#0#0#Wenn ein Schiff von einem Freezer getroffen wird, kann er sich fuer 6 Sekunden nicht bewegen." )
set_string( MENU_SHIP_WI_SHRINKER,        "Shrinker#0#0#0#Der Shrinker verkleinert feindliche Spieler fuer 20 Sekunden. Verkleinerte Spieler koennen nicht schiessen und man kann sie einfach rammen." )
set_string( MENU_SHIP_WI_PROBE,           "Sonde#1 (10)#1 (6)#1 (10)#Die Sonde, in der Naehe des Gegners platziert, verfolgt diesen und beschiesst ihn fuer 10 Sekunden. Die Werte in Klammern gelten fuer eine direkte Kollision." )
set_string( MENU_SHIP_WI_GAS,             "Delirium-Bombe#0#0#0#Die Delirium-Bombe explodiert nach 2 Sekunden. Jeder Spieler, der durch das Gasfeld fliegt, erleidet verwirrende, aber voruebergehende Deliriums-Effekte. Gut zum Abhaengen von Gegnern." )
set_string( MENU_SHIP_WI_LASER,           "Laser#2#3#0#Der Laser eignet sich gut zur Schwaechung gegnerischer Schilde. Gegen die Huelle ist er nutzlos." )
set_string( MENU_SHIP_WI_BUMPER,          "Bumper-Bombe#0#0#0#Trifft die Bumper-Bombe einen gegnerischen Spieler, wird dieser von der Wucht weggeschleudert. Diese Bombe schwaecht nur die Wandschilde." )
set_string( MENU_SHIP_WI_SHOTGUN,         "Schrotflinte#1#0#1#Die Schrotflinte ist die ideale Defensivwaffe. Sie zerstoert die meisten gegnerischen Raketen und Sonden. Allerdings ist sie nutzlos gegen Schilde.")
set_string( MENU_SHIP_WI_ACID,            "Saeure#1#0#1#Die Saeure durchdringt problemlos Schilde (Designschwaeche) und frisst sich in die Huelle.")
set_string( MENU_SHIP_SLOT1,              "Sch. 1" )
set_string( MENU_SHIP_SLOT2,              "Sch. 2" )
set_string( MENU_SHIP_SLOT3,              "Sch. 3" )
set_string( MENU_SHIP_SLOT4,              "Sch. 4" )
set_string( MENU_SHIP_SLOT5,              "Sch. 5" )
set_string( MENU_SHIP_SLOT6,              "Sch. 6" )
set_string( MENU_SHIP_DAMAGE_SP,          "Einspielermodus" )
set_string( MENU_SHIP_DAMAGE_MP,          "Schaden" )


-- single player
set_string( MENU_CAP_SINGLEPLAYER,        "Ein Spieler Mission" )
set_string( MENU_CAP_MINIGAME,            "Minispiel" )
set_string( MENU_DISP_RACES,              "Rennen" )
set_string( MENU_DISP_MISSIONS,           "Missionen" )
set_string( MENU_DISP_DOGFIGHTS,          "Dogfights" )
set_string( MENU_CAP_AUTHOR,              "Level-Autor" )
set_string( MENU_LEVEL_LOCKED,            "Dieser Level ist gesperrt" )

-- twoplayer dogfight
set_string( MENU_CAP_SPLITSCREEN,         "Splitscreen Match" )
set_string( MENU_PLAY,                    "Kaempfen!" )
set_string( MENU_PLAY_MINIGAME,           "Spielen!" )
set_string( MENU_NAME_P1,                 "Name Spieler 1" )
set_string( MENU_NAME_P2,                 "Name Spieler 2" )
set_string( MENU_2P_CHOOSESHIP,           "Schiff waehlen" )
set_string( MENU_2P_EDITSHIP,             "Schiff bearbeiten" )
set_string( MENU_GRAVITY,                 "Gravitation" )
set_string( MENU_MAXFRAGS,                "Max Frags" )
set_string( MENU_MAXTIME,                 "Max Zeit" )
set_string( MENU_EXTRAS,                  "Extras" )
set_string( MENU_ONESCREEN_MAP,           "Ein-Bildschirm-Karte" )
set_string( MENU_SCRIPTING,               "Scripting" )
set_string( MENU_LEVELEXTRA,              "Extra aktivieren" )
set_string( MENU_CAPTURE_THE_FLAG,        "Capture the Flag" )
set_string( MENU_HUNTER_HUNTED,           "Hunter-Hunted" )
set_string( MENU_LAPS,                    "Runden" )
set_string( MENU_COMPUTER_PLAYER,         "Spieler 2 = Computer" )
set_string( MENU_COMPUTER_PLAYER_STRENGTH, "Staerke" )
set_string( MENU_2NDPLAYER,               "2 Spieler" )
set_string( MENU_LEVELINFO,               "Levelinfo" )
set_string( MENU_HANDICAP,                "Handicap / Fairplay-Modus" )


-- network game
set_string( MENU_CAP_NETGAME,             "Netzwerkspiel" )
set_string( MENU_CAP_NETGAME_SERVER,      "Netzwerkspiel - Server" )
set_string( MENU_CAP_NETGAME_CLIENT,      "Netzwerkspiel - Client" )
set_string( MENU_SERVER,                  "Spiel erstellen (Server)" )
set_string( MENU_CLIENT,                  "Spiel beitreten (Client)" )
set_string( MENU_READY,                   "bereit" )
set_string( MENU_I_AM_READY,              "Ok, ich bin bereit..." )
set_string( MENU_LEVEL_NOT_AVAILABLE,     "Level nicht verfuegbar!" )

-- ingame
set_string( GAME_EXTRA,                   "Extra" )
set_string( GAME_AMMOPACK,                "Munition" )
set_string( GAME_TIME,                    "Zeit" )
set_string( GAME_TIMEREM,                 "Verbleibende Zeit" )
set_string( GAME_CARGO,                   "Fracht" )
set_string( GAME_MAN,                     "Ein Mensch" )
set_string( GAME_SOMETHING,               "Irgendwas..." )
set_string( GAME_WEIGHT,                  "Gewicht" )
set_string( GAME_CARGOREC,                "Fracht erhalten" )
set_string( GAME_HOMEBASE,                "Heimatbasis" )
set_string( GAME_PANEL_FUEL,              "TREIB" )
set_string( GAME_PANEL_EXTRA,             "EXTRA" )
set_string( GAME_PANEL_FRAGS,             "ABSCH" )
set_string( GAME_PANEL_SHIPS,             "SHIPS" )
set_string( GAME_MISSION_DONE,            "MISSION KOMPLETT!" )
set_string( GAME_MISSION_FAILED,          "MISSION FEHLGESCHLAGEN..." )
set_string( GAME_YOU_ARE_DEAD,            "SIE SIND TOT." )
set_string( GAME_EXTRA_UPGRADE,           "Waffen-Upgrade" )
set_string( GAME_EXTRA_FUEL,              "Treibstoff" )
set_string( GAME_EXTRA_FULLSHIELD,        "Voller Schild/Huelle" )
set_string( GAME_EXTRA_FULLWSHIELD,       "Voller Wandschild" )
set_string( GAME_EXTRA_INVULNERABILITY,   "Unzerstoerbarkeit" )
set_string( GAME_DAMAGE,                  "SCHADEN" )
set_string( GAME_DAMAGE_THRUSTER,         "Antrieb" )
set_string( GAME_DAMAGE_STEERING,         "Steuerung" )
set_string( GAME_DAMAGE_FUEL,             "Treibstoffleck" )
set_string( GAME_DAMAGE_WEAPONS,          "Waffensystem" )
set_string( GAME_DAMAGE_SHIELD,           "Schildsystem" )
set_string( GAME_DAMAGE_LANDING,          "Landestabilisatoren" )
set_string( GAME_DAMAGE_RADAR,            "Radarsystem" )
set_string( GAME_ESC_EXIT,		  "Level beenden" )
set_string( GAME_ESC_RESTART,	          "Level neu starten" )
set_string( GAME_ESC_OTHER_KEY,           "Andere" )
set_string( GAME_ESC_CONTINUE,            "Weiterspielen" )

-- statistics screen
set_string( STATS_CAP_1PLAYER,            "Missions-Statistik" )
set_string( STATS_CAP_2PLAYER,            "2-Spieler Statistik" )
set_string( STATS_CAP_NETWORK,            "Netzwerkspiel-Statistik" )
set_string( STATS_MODE,                   "Spielmodus" )
set_string( STATS_MODE_DOGFIGHT,          "Dogfight" )
set_string( STATS_MODE_RACE,              "Rennen" )
set_string( STATS_PLAYER,                 "Spieler" )
set_string( STATS_HITPERCENT,             "Treffergenauigkeit" )
set_string( STATS_FRAGS,                  "Abschuesse" )
set_string( STATS_SUICIDES,               "Selbstmorde" )
set_string( STATS_EXTRASTAKEN,            "Aufgen. Extras" )
set_string( STATS_WINNER,                 "Gewinner" )
set_string( STATS_DRAW,                   "Unentschieden" )
set_string( STATS_PLACE,                  "Platz" )
set_string( STATS_SCORE,                  "Punkte" )
set_string( STATS_LAP,                    "Runde" )
set_string( STATS_TIME,                   "Zeit" )
set_string( STATS_OVERALL_TIME,           "Gesamtzeit" )
set_string( STATS_TIMEPLAYED,             "Gespielte Zeit" )
set_string( STATS_BONUS,                  "Bonuspunkte" )
set_string( STATS_ENEMY_BONUS,            "Gegner-Bonus" )
set_string( STATS_LOSTLIFES,              "Verlorene Schiffe" )
set_string( STATS_MISSION_STATUS,         "Missions-Status" )
set_string( STATS_COMPLETED,              "abgeschlossen" )
set_string( STATS_FAILED,                 "fehlgeschlagen" )
set_string( STATS_HISCORE_NEW,            "Gratulation, Sie haben Ihren Highscore erhoeht!" )
set_string( STATS_HISCORE_OLD,            "Sorry, Ihr letzter Highscore war besser..." )
set_string( STATS_HISCORE_DISABLED,       "Highscores deaktiviert" )

-- frag messages (network)

set_string( NET_FRAGMSG_SINGLE_BLASTER_1, "%1% pustet %2% weg" )
set_string( NET_FRAGMSG_SINGLE_BLASTER_2, "%1%s Blaster war zuviel fuer %2%" )
set_string( NET_FRAGMSG_SINGLE_BLASTER_3, "%2% unterliegt %1%s Blaster" )
set_string( NET_FRAGMSG_SINGLE_BLASTER_4, "%1% erwischt %2% mit dem Normalo-Blaster" )
set_string( NET_FRAGMSG_SINGLE_BLASTER_5, "%2% wurde von %1% zu Pixelstaub verarbeitet" )

set_string( NET_FRAGMSG_DOUBLE_BLASTER_1, "%1% durchloechert %2%" )
set_string( NET_FRAGMSG_DOUBLE_BLASTER_2, "%1% perforiert %2%" )
set_string( NET_FRAGMSG_DOUBLE_BLASTER_3, "%2% unterliegt %1%s Double Blaster" )
set_string( NET_FRAGMSG_DOUBLE_BLASTER_4, "%1%s Doppelblaster schlaegt bei %2% zu" )
set_string( NET_FRAGMSG_DOUBLE_BLASTER_5, "%2% geraet in %1%s Doppelfeuer" )

set_string( NET_FRAGMSG_BOMB_1,           "%1%s Bomben waren zuviel fuer %2%" )
set_string( NET_FRAGMSG_BOMB_2,           "%1% bombt %2% weg" )
set_string( NET_FRAGMSG_BOMB_3,           "%2% unterliegt %1%s Bomben" )
set_string( NET_FRAGMSG_BOMB_4,           "Das war eine Bombe zu viel fuer %2%" )
set_string( NET_FRAGMSG_BOMB_5,           "Die Bombenflugbahn zu %2% hat %1% gut berechnet" )

set_string( NET_FRAGMSG_BIGBOMB_1,        "%2% verbrennt in %1%s Feuerball" )
set_string( NET_FRAGMSG_BIGBOMB_2,        "%1%s Bigbomb zerfetzt %2%" )
set_string( NET_FRAGMSG_BIGBOMB_3,        "%2% kann %1%s Bigbomb nicht ausweichen" )
set_string( NET_FRAGMSG_BIGBOMB_4,        "%2% verliert gegen eine exakt abgeworfene Bigbomb" )
set_string( NET_FRAGMSG_BIGBOMB_5,        "%1% verbrennt %2% gewaltig" )

set_string( NET_FRAGMSG_ROCKET_1,         "%1%s Raketen zerjagen %2%" )
set_string( NET_FRAGMSG_ROCKET_2,         "%2% wurde weggejagt" )
set_string( NET_FRAGMSG_ROCKET_3,         "%2% konnte %1%s Raketen nicht mehr ausweichen" )
set_string( NET_FRAGMSG_ROCKET_4,         "%1% erwischt %2%, ohne selber zu zielen" )
set_string( NET_FRAGMSG_ROCKET_5,         "%1% holt %2% per Rakete zurueck auf den Boden" )

set_string( NET_FRAGMSG_MINE_1,           "%2% fliegt in %1%s Minen" )
set_string( NET_FRAGMSG_MINE_2,           "%1%s Minen zerstoeren %2%" )
set_string( NET_FRAGMSG_MINE_3,           "%2% fliegt in %1%s Minenfeld" )
set_string( NET_FRAGMSG_MINE_4,           "%2% hat wohl den Minensucher vergessen" )
set_string( NET_FRAGMSG_MINE_5,           "Da hat %2% eindeutig auf Metall gebissen" )

set_string( NET_FRAGMSG_SHRINKER_1,       "%2% stirbt als Liliputaner" )
set_string( NET_FRAGMSG_SHRINKER_2,       "%2% wuenschte sich, wieder gross zu sein" )
set_string( NET_FRAGMSG_SHRINKER_3,       "%1% zerstoert den kleinen %2%" )
set_string( NET_FRAGMSG_SHRINKER_4,       "Zwerg %2% konnte vor %1% nicht mehr fliehen" )
set_string( NET_FRAGMSG_SHRINKER_5,       "Versehentlich trampelt %1% auf %2%" )

set_string( NET_FRAGMSG_PROBE_1,          "%2% hat keine Chance gegen %1%s Sonde" )
set_string( NET_FRAGMSG_PROBE_2,          "%1% laesst andere fuer sich arbeiten und zerstoert %2%" )
set_string( NET_FRAGMSG_PROBE_3,          "%1%s Sonde war schon wieder erfolgreich gegen %2%" )
set_string( NET_FRAGMSG_PROBE_4,          "%2% geht in %1%s Sonden-Kreuzfeuer unter" )
set_string( NET_FRAGMSG_PROBE_5,          "%2% verliert gegen %1%s Sonden-Geschwader" )

set_string( NET_FRAGMSG_GAS_1,            "%2% stirbt im Delirium" )
set_string( NET_FRAGMSG_GAS_2,            "%2% fliegt bedusselt vor eine Wand" )
set_string( NET_FRAGMSG_GAS_3,            "%2% hat wohl einen zu viel gekippt" )
set_string( NET_FRAGMSG_GAS_4,            "%2% verliert sich im Psychorama" )
set_string( NET_FRAGMSG_GAS_5,            "%2% sieht nur noch bunte Bilder" )

set_string( NET_FRAGMSG_BUMPER_1,         "%1% schleudert %2% weg" )
set_string( NET_FRAGMSG_BUMPER_2,         "%1%s Bumper Bomb erwischt %2%" )
set_string( NET_FRAGMSG_BUMPER_3,         "War wohl ein Bumper zu viel fuer %2%" )
set_string( NET_FRAGMSG_BUMPER_4,         "%1% hat %2% ein wenig umher geschubst" )
set_string( NET_FRAGMSG_BUMPER_5,         "%1% drischt %2% vom Spielfeld" )

set_string( NET_FRAGMSG_SHOTGUN_1,        "%1% perforiert %2%" )
set_string( NET_FRAGMSG_SHOTGUN_2,        "%2% wurde perforiert" )
set_string( NET_FRAGMSG_SHOTGUN_3,        "%1% pumpt %2% voller Schrot" )
set_string( NET_FRAGMSG_SHOTGUN_4,        "%2% kommt %1%s Schrotflinte zu nahe" )
set_string( NET_FRAGMSG_SHOTGUN_5,        "%2% geht in %1%s Kugelhagel unter" )

set_string( NET_FRAGMSG_ACID_1,           "%1% zerfrisst %2%" )
set_string( NET_FRAGMSG_ACID_2,           "%2% wurde aufgefressen" )
set_string( NET_FRAGMSG_ACID_3,           "%1% pumpt %2% voll mit Saeure" )
set_string( NET_FRAGMSG_ACID_4,           "%1% pumpt %2% voll mit Saeure" )
set_string( NET_FRAGMSG_ACID_5,           "%2% versauert" )

set_string( NET_FRAGMSG_SUICIDE_1,        "%2% toetet sich selbst" )
set_string( NET_FRAGMSG_SUICIDE_2,        "%2% kann nicht mehr fliegen" )
set_string( NET_FRAGMSG_SUICIDE_3,        "%2% rast in eine Wand" )
set_string( NET_FRAGMSG_SUICIDE_4,        "%2% zerschellt an einer Ecke" )
set_string( NET_FRAGMSG_SUICIDE_5,        "%2% landet im Graben" )

set_string( NET_FRAGMSG_PLSUICIDE_1,      "%2% wurde weggerammt" )
set_string( NET_FRAGMSG_PLSUICIDE_2,      "%2%s Schiff war schwaecher als %1%s..." )
set_string( NET_FRAGMSG_PLSUICIDE_3,      "%2% rast in %1%" )
set_string( NET_FRAGMSG_PLSUICIDE_4,      "%2% sollte besser Abstand halten" )
set_string( NET_FRAGMSG_PLSUICIDE_5,      "%2% wurde ueberrollt" )

set_string( NET_FRAGMSG_JOIN_1,           "%1% kommt ins Spiel" )
set_string( NET_FRAGMSG_JOIN_2,           "%1% beehrt die froehliche Runde" )
set_string( NET_FRAGMSG_JOIN_3,           "%1% spielt nun auch mit" )
set_string( NET_FRAGMSG_JOIN_4,           "%1% betritt das Schlachtfeld" )
set_string( NET_FRAGMSG_JOIN_5,           "%1% ist neu hier" )

set_string( NET_FRAGMSG_QUIT_1,           "%1% verlaesst das Spiel" )
set_string( NET_FRAGMSG_QUIT_2,           "%1% hat genug und geht" )
set_string( NET_FRAGMSG_QUIT_3,           "%1% hat keine Lust mehr" )
set_string( NET_FRAGMSG_QUIT_4,           "%1% zieht vom Schlachtfeld ab" )
set_string( NET_FRAGMSG_QUIT_5,           "%1% packt seine Sachen und geht nach Hause" )

set_string( NET_JOIN_LOBBY,               "hat die Lobby betreten" )
set_string( NET_LEAVE_LOBBY,              "hat die Lobby verlassen" )


-- controls
set_string( MENU_CAP_CONTROLS,            "Spieler-Kontrollen" )
set_string( MENU_CAP_2PCONTROLS,          "2-Spieler-Kontrollen" )
set_string( MENU_CAP_SPCONTROLS,          "Spezialtasten" )
set_string( MENU_TEXT_PLAYER1,            "Erster Spieler" )
set_string( MENU_TEXT_PLAYER2,            "Zweiter Spieler" )
set_string( CONTROL_LEFT,                 "Links drehen" )
set_string( CONTROL_RIGHT,                "Rechts drehen" )
set_string( CONTROL_THRUST,               "Triebwerke" )
set_string( CONTROL_SHOOT,                "Schiessen" )
set_string( CONTROL_NEXTWEAP,             "Naechste Waffe" )
set_string( CONTROL_PREVWEAP,             "Vorherige Waffe" )
set_string( CONTROL_W1,                   "Waffe 1" )
set_string( CONTROL_W2,                   "Waffe 2" )
set_string( CONTROL_W3,                   "Waffe 3" )
set_string( CONTROL_W4,                   "Waffe 4" )
set_string( CONTROL_W5,                   "Waffe 5" )
set_string( CONTROL_W6,                   "Waffe 6" )
set_string( CONTROL_EXTRA_ACTION,         "Extra-Aktion" )
set_string( CONTROL_EXTRA2,               "Spezial" )
set_string( CONTROL_PAUSE,	          "Pause" )
set_string( CONTROL_SCREENSHOT,           "Screenshot" )
set_string( CONTROL_PANEL,                "Panel an/aus" )
set_string( CONTROL_DEBUG,                "Debug-Meldungen" )
set_string( CONTROL_CHAT,                 "Chat" )

-- keyboard
set_string( KEY_LCONTROL,                 "STRG Links" )
set_string( KEY_RCONTROL,                 "STRG Rechts" )
set_string( KEY_ALT,                      "Alt Links" )
set_string( KEY_ALTGR,                    "Alt Gr" )
set_string( KEY_LSHIFT,                   "Shift Links" )
set_string( KEY_RSHIFT,                   "Shift Rechts" )
set_string( KEY_SPACE,                    "Leertaste" )
set_string( KEY_LWIN,                     "Links Win" )
set_string( KEY_RWIN,                     "Rechts Win" )
set_string( KEY_MENU,                     "Win Menu" )
set_string( KEY_TAB,                      "TAB" )
set_string( KEY_ENTER,                    "Enter" )
set_string( KEY_BACKSPACE,                "Backspace" )
set_string( KEY_MINUS,                    "Minus" )
set_string( KEY_ESC,                      "Escape" )
set_string( KEY_TILDE,                    "Tilde ~")
set_string( KEY_EQUALS,                   "Gleich =" )
set_string( KEY_OPENBRACE,                "Klammer auf" )
set_string( KEY_CLOSEBRACE,               "Klammer zu" )
set_string( KEY_COLON,                    "Doppelpunkt" )
set_string( KEY_QUOTE,                    "Anf.zeichen" )
set_string( KEY_BACKSLASH,                "Backslash" )
set_string( KEY_BACKSLASH2,               "Backslash 2" )
set_string( KEY_COMMA,                    "Komma" )
set_string( KEY_STOP,                     "Punkt" )
set_string( KEY_SLASH,                    "Slash" )
set_string( KEY_NUMLOCK,                  "Num Lock" )
set_string( KEY_CAPSLOCK,                 "Capslock" )
set_string( KEY_SCRLOCK,                  "Scroll Lock" )
set_string( KEY_F1,                       "F1" )
set_string( KEY_F2,                       "F2" )
set_string( KEY_F3,                       "F3" )
set_string( KEY_F4,                       "F4" )
set_string( KEY_F5,                       "F5" )
set_string( KEY_F6,                       "F6" )
set_string( KEY_F7,                       "F7" )
set_string( KEY_F8,                       "F8" )
set_string( KEY_F9,                       "F9" )
set_string( KEY_F10,                      "F10" )
set_string( KEY_F11,                      "F11" )
set_string( KEY_F12,                      "F12" )
set_string( KEY_PRTSCR,                   "Print Screen" )
set_string( KEY_PAUSE,                    "Pause" )
set_string( KEY_INSERT,                   "Einfg" )
set_string( KEY_DEL,                      "Entf" )
set_string( KEY_HOME,                     "Pos1" )
set_string( KEY_END,                      "Ende" )
set_string( KEY_PGUP,                     "Bild auf" )
set_string( KEY_PGDN,                     "Bild ab" )
set_string( KEY_LEFT,                     "Pfeil links" )
set_string( KEY_RIGHT,                    "Pfeil rechts" )
set_string( KEY_UP,                       "Pfeil hoch" )
set_string( KEY_DOWN,                     "Pfeil runter" )
set_string( KEY_SLASH_PAD,                "Slash [Pad]" )
set_string( KEY_0_PAD,                    "0 [Pad]" )
set_string( KEY_1_PAD,                    "1 [Pad]" )
set_string( KEY_2_PAD,                    "2 [Pad]" )
set_string( KEY_3_PAD,                    "3 [Pad]" )
set_string( KEY_4_PAD,                    "4 [Pad]" )
set_string( KEY_5_PAD,                    "5 [Pad]" )
set_string( KEY_6_PAD,                    "6 [Pad]" )
set_string( KEY_7_PAD,                    "7 [Pad]" )
set_string( KEY_8_PAD,                    "8 [Pad]" )
set_string( KEY_9_PAD,                    "9 [Pad]" )
set_string( KEY_ENTER_PAD,                "Enter [Pad]" )
set_string( KEY_PLUS_PAD,                 "Plus [Pad]" )
set_string( KEY_MINUS_PAD,                "Minus [Pad]" )
set_string( KEY_ASTERISK,                 "Stern" )
set_string( JOY0_UP,                      "Joy 1: Hoch" )
set_string( JOY0_DOWN,                    "Joy 1: Runter" )
set_string( JOY0_LEFT,                    "Joy 1: Links" )
set_string( JOY0_RIGHT,                   "Joy 1: Rechts" )
set_string( JOY0_B1,                      "Joy 1: Knopf 1" )
set_string( JOY0_B2,                      "Joy 1: Knopf 2" )
set_string( JOY0_B3,                      "Joy 1: Knopf 3" )
set_string( JOY0_B4,                      "Joy 1: Knopf 4" )
set_string( JOY0_B5,                      "Joy 1: Knopf 5" )
set_string( JOY0_B6,                      "Joy 1: Knopf 6" )
set_string( JOY1_UP,                      "Joy 2: Hoch" )
set_string( JOY1_DOWN,                    "Joy 2: Runter" )
set_string( JOY1_LEFT,                    "Joy 2: Links" )
set_string( JOY1_RIGHT,                   "Joy 2: Rechts" )
set_string( JOY1_B1,                      "Joy 2: Knopf 1" )
set_string( JOY1_B2,                      "Joy 2: Knopf 2" )
set_string( JOY1_B3,                      "Joy 2: Knopf 3" )
set_string( JOY1_B4,                      "Joy 2: Knopf 4" )
set_string( JOY1_B5,                      "Joy 2: Knopf 5" )
set_string( JOY1_B6,                      "Joy 2: Knopf 6" )

-- other/misc
set_string( MENU_YES,                     "Ja" )
set_string( MENU_NO,                      "Nein" )
set_string( MENU_OK,                      "Okay" )

-- ===========================================================

-- CROATIAN LANGUAGE

elseif ( LANGUAGE == LANG_CR ) then

-- main menu
set_string( MENU_SINGLEPLAYER,            "Single Player" )
set_string( MENU_SPLITSCREEN,             "Igra Dva Igraca" )
set_string( MENU_MINIGAME,                "Mini Game" )
set_string( MENU_NETGAME,                 "Igra u Mrezi" )
set_string( MENU_OPTIONS,                 "Opcije" )
set_string( MENU_CREDITS,                 "Autor" )
set_string( MENU_SHIPBUILDER,             "Izgradnja Broda" )
set_string( MENU_BACK,                    "Natrag" )
set_string( MENU_QUIT,                    "Izlazak" )

-- options menu
set_string( MENU_CAP_OPTIONS,             "Igrace Opcije" )
set_string( MENU_LANGUAGE,                "Jezik" )
set_string( MENU_LANG_EN,                 "Hrvatski" )
set_string( MENU_LANG_DE,                 "Njemacki" )
set_string( MENU_LANG_CR,                 "Croatian" )
set_string( MENU_PIXAMOUNT,               "Pixel Efekti" )
set_string( MENU_VOLUME,                  "Glasnoca" )
set_string( MENU_MVOLUME,                 "Music Volume" )
set_string( MENU_CONTROLS,                "Kontrole" )
set_string( MENU_2PCONTROLS,              "Kontr.2 Igraca" )
set_string( MENU_SPCONTROLS,              "Special Controls" )
set_string( MENU_RESOLUTION,	          "Game Resolution" )

-- ship builder (choose ship)
set_string( MENU_CAP_CHOOSESHIP,          "Izaberi Brod" )
set_string( MENU_NEWSHIP,                 "NoviBrod" )
set_string( MENU_NEXTPAGE,                "Sljed.Stranica" )
set_string( MENU_LASTPAGE,                "Preth.Stranica" )

-- ship builder
set_string( MENU_CAP_SHIPBUILDER,         "Izgradnja Broda" )
set_string( MENU_MSG_SHIPLOADERROR,       "Greska u Ucitavanju Broda!" )
set_string( MENU_MSG_REALLYDELETE,        "Zaista Izbrisati Ovaj Brod?" )
set_string( MENU_EDITWEAPONS,             "Odab. Oruzja" )
set_string( MENU_EDITSHIP,                "Osobine Broda" )
set_string( MENU_SAVE,                    "Snimi" )
set_string( MENU_SAVENEW,                 "Snimi Novo" )
set_string( MENU_DELETE,                  "Izbrisi" )
set_string( MENU_SHIP_NAME,               "Naziv" )
set_string( MENU_SHIP_DESC,               "Opis" )
set_string( MENU_SHIP_LOADIMAGE,          "Unesi Image" )
set_string( MENU_SHIP_LOADIMAGE_FS,       "Ucitaj Image (BMP, PCX, TGA)" )
set_string( MENU_SHIP_REMPOINTS,          "Preostala Energija" )
set_string( MENU_SHIP_HULL,               "Trup" )
set_string( MENU_SHIP_SHIELD,             "Stitovi" )
set_string( MENU_SHIP_HULL_RE,            "Popravak Trupa" )
set_string( MENU_SHIP_SHIELD_RE,          "Obnavljanje Stita" )
set_string( MENU_SHIP_WEAPON_RE,          "Obnavljanje Oruzja" )
set_string( MENU_SHIP_RADAR_ZOOM,         "Radar. Povecanje" )
set_string( MENU_SHIP_WEAPON_SLOTS,       "Nosaci Oruzja" )
set_string( MENU_SHIP_TURN_SPEED,         "Brzina Zaokreta" )
set_string( MENU_SHIP_MAX_SPEED,          "Max Brzina" )
set_string( MENU_SHIP_ACCELERATION,       "Ubrzanje" )
set_string( MENU_SHIP_FUEL_CONSUMPTION,   "Potrosnja Goriva" )
set_string( MENU_SHIP_WEAPON_STORAGE,     "Prostor za Oruzje" )
set_string( MENU_SHIP_EXTRA,              "Dodaci" )
set_string( MENU_SHIP_AFTERBURNER,        "Forsaz" )
set_string( MENU_SHIP_DEFLECTOR,          "Deflector" )
set_string( MENU_SHIP_CLOAK,              "Prikriveni Mod" )
set_string( MENU_SHIP_WEAPONS,            "Oruzje" )
set_string( MENU_SHIP_TEXT_WEAPAVAIL,     "Raspolozivo Oruzje" )
set_string( MENU_SHIP_TEXT_WEAPSLOTS,     "Nosaci Oruzja" )
set_string( MENU_SHIP_TEXT_WEAPDESC,      "Opis" )
set_string( MENU_SHIP_W_SBLASTER,         "Jednostruki Blaster" )
set_string( MENU_SHIP_W_DBLASTER,         "Dvostruki Blaster" )
set_string( MENU_SHIP_W_BOMB,             "Bomba" )
set_string( MENU_SHIP_W_BIGBOMB,          "Velika Bomba" )
set_string( MENU_SHIP_W_ROCKETS,          "Rakete" )
set_string( MENU_SHIP_W_MINES,            "Mine" )
set_string( MENU_SHIP_W_FREEZER,          "Zamrzivac" )
set_string( MENU_SHIP_W_SHRINKER,         "Smanjivac" )
set_string( MENU_SHIP_W_PROBE,            "Sonda" )
set_string( MENU_SHIP_W_GAS,              "Delirij Bomba" )
set_string( MENU_SHIP_W_LASER,            "Laser" )
set_string( MENU_SHIP_W_BUMPER,           "Bumper Bomb" )
set_string( MENU_SHIP_W_SHOTGUN,          "Shotgun" )
set_string( MENU_SHIP_W_Acid,             "Acid" )
set_string( MENU_SHIP_WI_SBLASTER,        "Jednostruki Blaster#1#1#1#Jednostruki Blaster je standardno oruzje na svim brodovima. Nije osobito snazan, ali meci su precizni i brzi." )
set_string( MENU_SHIP_WI_DBLASTER,        "Dvostruki Blaster#2#1#2#Dvostruki Blaster objedinjuje brzinu i preciznost Single Blastera s vecim stupnjem ostecenja." )
set_string( MENU_SHIP_WI_BOMB,            "Bomba#2#2#2#Bomba eksplodira u osam fragmenata koji se sire u osam smjerova." )
set_string( MENU_SHIP_WI_BIGBOMB,         "Velika Bomba#25#15#20#Velika Bomba jednostavno ispada iz tvog nosaca oruzja krecuci se u smjeru gravitacije. To je najjace oruzje." )
set_string( MENU_SHIP_WI_ROCKETS,         "Rakete#6#6#3#Rakete se automatski navode u smjeru najblizeg cilja." )
set_string( MENU_SHIP_WI_MINES,           "Mine#15 (max)#15 (max)#10 (max)#Mine su nepomicno oruzje koje eksplodira kad neprijatelj udje u zonu aktiviranja. Ostecenje od njihove eksplozije ovisi o udaljenosti." )
set_string( MENU_SHIP_WI_FREEZER,         "Freezer#0#0#0#Kad Zamrzivac pogodi igraca, on ostaje nepokretan 6 sekunde. Dovoljno vremena da ga upucas." )
set_string( MENU_SHIP_WI_SHRINKER,        "Shrinker#0#0#0#Smanjivac smanjuje neprijatelja u mali brod-igracku (20 sekundi). Smanjeni igraci ne mogu pucati i mozes im jednostavno prici i unistiti ih." )
set_string( MENU_SHIP_WI_PROBE,           "Sonda#1 (10)#1 (6)#1 (10)#Sonda, pustena blizu neprijatelja, slijedi ga pucajuci na njega 10 sekundi." )
set_string( MENU_SHIP_WI_GAS,             "Delirij Bomba#0#0#0#Delirij Bomba eksplodira nakon 2 sekunde. Tada svaki neprijatelj koji proleti kroz oblak dobija napad delirija. Odlicno da se oslobodis proganjajuceg neprijatelja." )
set_string( MENU_SHIP_WI_LASER,           "Laser#2#3#0#The laser with its fast shots is great for weakening shields (2 hitpoints). But beware: It is not effective against the hull." )
set_string( MENU_SHIP_WI_BUMPER,          "Bumper Bomb#0#0#0#When the Bumper Bomb hits another player, his ship accelerates in the bomb's direction. This bomb only affects wall shields." )
set_string( MENU_SHIP_WI_SHOTGUN,         "Shotgun#1#0#1#The Shotgun is the ideal defensive weapon. It takes out most rockets and probes, but it is only effective against the hull.")
set_string( MENU_SHIP_WI_ACID,            "Acid#1#0#1#The Acid penetrates shields (design leak) and affects the integrity of the hull." )
set_string( MENU_SHIP_SLOT1,              "Nosac 1" )
set_string( MENU_SHIP_SLOT2,              "Nosac 2" )
set_string( MENU_SHIP_SLOT3,              "Nosac 3" )
set_string( MENU_SHIP_SLOT4,              "Nosac 4" )
set_string( MENU_SHIP_SLOT5,              "Nosac 5" )
set_string( MENU_SHIP_SLOT6,              "Nosac 6" )
set_string( MENU_SHIP_DAMAGE_SP,          "Singleplayer" )
set_string( MENU_SHIP_DAMAGE_MP,          "Damage" )

-- single player
set_string( MENU_CAP_SINGLEPLAYER,        "Single Player Mission" )
set_string( MENU_CAP_MINIGAME,            "Mini Game" )
set_string( MENU_DISP_RACES,              "Races" )
set_string( MENU_DISP_MISSIONS,           "Missions" )
set_string( MENU_DISP_DOGFIGHTS,          "Dogfights" )
set_string( MENU_CAP_AUTHOR,              "Level Author" )
set_string( MENU_LEVEL_LOCKED,            "This level is locked" )

-- twoplayer dogfight
set_string( MENU_CAP_SPLITSCREEN,         "Borba na Podijeljenom Ekranu" )
set_string( MENU_PLAY,                    "Borba!" )
set_string( MENU_PLAY_MINIGAME,           "Play!" )
set_string( MENU_NAME_P1,                 "Ime 1. Igraca" )
set_string( MENU_NAME_P2,                 "Ime 2. Igraca" )
set_string( MENU_2P_CHOOSESHIP,           "Izaberi Brod" )
set_string( MENU_2P_EDITSHIP,             "Osobine Broda" )
set_string( MENU_GRAVITY,                 "Gravitacija" )
set_string( MENU_MAXFRAGS,                "Max Frag" )
set_string( MENU_MAXTIME,                 "Max Vrijeme" )
set_string( MENU_EXTRAS,                  "Dodaci" )
set_string( MENU_ONESCREEN_MAP,           "Ekranska Mapa" )
set_string( MENU_SCRIPTING,               "Ingame Scripting" )
set_string( MENU_LEVELEXTRA,              "Aktiviraj Dodatak" )
set_string( MENU_CAPTURE_THE_FLAG,        "Osvoji Zastavu" )
set_string( MENU_HUNTER_HUNTED,           "Lovac-Lovina" )
set_string( MENU_LAPS,                    "Laps" )
set_string( MENU_COMPUTER_PLAYER,         "Player 2 = Computer Player" )
set_string( MENU_COMPUTER_PLAYER_STRENGTH, "Strength" )
set_string( MENU_2NDPLAYER,               "2 Players" )
set_string( MENU_LEVELINFO,               "Level info" )
set_string( MENU_HANDICAP,                "Handicap / Fairplay Mode" )

-- network game
set_string( MENU_CAP_NETGAME,             "Igra u Mrezi" )
set_string( MENU_CAP_NETGAME_SERVER,      "Igra u Mrezi - Server" )
set_string( MENU_CAP_NETGAME_CLIENT,      "Igra u Mrezi - Client" )
set_string( MENU_SERVER,                  "Kreiraj Novu Igru" )
set_string( MENU_CLIENT,                  "Pridruzi se Igri" )
set_string( MENU_READY,                   "Spreman" )
set_string( MENU_I_AM_READY,              "OK, Ja Sam Spreman" )

-- ingame
set_string( GAME_EXTRA,                   "Dodatak" )
set_string( GAME_AMMOPACK,                "Municija" )
set_string( GAME_TIME,                    "Vrijeme" )
set_string( GAME_TIMEREM,                 "Preostalo Vrijeme" )
set_string( GAME_CARGO,                   "Teret" )
set_string( GAME_MAN,                     "Covjek" )
set_string( GAME_SOMETHING,               "Nesto..." )
set_string( GAME_WEIGHT,                  "Tezina" )
set_string( GAME_CARGOREC,                "Primljeni Teret" )
set_string( GAME_HOMEBASE,                "Maticna Baza" )
set_string( GAME_PANEL_FUEL,              "FUEL" )
set_string( GAME_PANEL_EXTRA,             "EXTRA" )
set_string( GAME_PANEL_FRAGS,             "FRAGS" )
set_string( GAME_PANEL_SHIPS,             "SHIPS" )
set_string( GAME_MISSION_DONE,            "MISSION DONE!" )
set_string( GAME_MISSION_FAILED,          "MISSION FAILED..." )
set_string( GAME_YOU_ARE_DEAD,            "YOU ARE DEAD." )
set_string( GAME_EXTRA_UPGRADE,           "Weapon Upgrade" )
set_string( GAME_EXTRA_FUEL,              "Fuel" )
set_string( GAME_EXTRA_FULLSHIELD,        "Full Shield/Hull" )
set_string( GAME_EXTRA_FULLWSHIELD,       "Full Wall Shield" )
set_string( GAME_EXTRA_INVULNERABILITY,   "Indestructibility" )
set_string( GAME_DAMAGE,                  "DAMAGE" )
set_string( GAME_DAMAGE_THRUSTER,         "Thrusters" )
set_string( GAME_DAMAGE_STEERING,         "Steering" )
set_string( GAME_DAMAGE_FUEL,             "Fuel Leak" )
set_string( GAME_DAMAGE_WEAPONS,          "Weapon system" )
set_string( GAME_DAMAGE_SHIELD,           "Shield system" )
set_string( GAME_DAMAGE_LANDING,          "Landing Stabilizers" )
set_string( GAME_DAMAGE_RADAR,            "Radar System" )
set_string( GAME_ESC_EXIT,		  "Exit Level" )
set_string( GAME_ESC_RESTART,	          "Restart Level" )
set_string( GAME_ESC_OTHER_KEY,           "Other" )
set_string( GAME_ESC_CONTINUE,            "Continue" )

-- statistics screen
set_string( STATS_CAP_1PLAYER,            "Statistika 1 Igraca" )
set_string( STATS_CAP_2PLAYER,            "Statistika 2 Igraca" )
set_string( STATS_MODE,                   "Mod Igre" )
set_string( STATS_MODE_DOGFIGHT,          "Prsa o Prsa" )
set_string( STATS_MODE_RACE,              "Utrka" )
set_string( STATS_PLAYER,                 "Igrac" )
set_string( STATS_HITPERCENT,             "Postotak Pogotka" )
set_string( STATS_FRAGS,                  "Frags" )
set_string( STATS_SUICIDES,               "Samoubojstva" )
set_string( STATS_EXTRASTAKEN,            "Uzetih Dodataka" )
set_string( STATS_WINNER,                 "Pobjednik" )
set_string( STATS_DRAW,                   "Nerijeseno" )
set_string( STATS_PLACE,                  "Mjesto" )
set_string( STATS_SCORE,                  "Rezultat" )
set_string( STATS_LAP,                    "Krug" )
set_string( STATS_TIME,                   "Vrijeme" )
set_string( STATS_OVERALL_TIME,           "Ukupno Vrijeme" )
set_string( STATS_TIMEPLAYED,             "Odigrano Vrijeme" )
set_string( STATS_BONUS,                  "Bonus Bodovi" )
set_string( STATS_ENEMY_BONUS,            "Enemy Bonus" )
set_string( STATS_LOSTLIFES,              "Lost Ships" )
set_string( STATS_MISSION_STATUS,         "Mission status" )
set_string( STATS_COMPLETED,              "completed" )
set_string( STATS_FAILED,                 "failed" )
set_string( STATS_HISCORE_NEW,            "Gratulations, you bet your last highscore!" )
set_string( STATS_HISCORE_OLD,            "Sorry, you didn't bet your last score..." )
set_string( STATS_HISCORE_DISABLED,       "Highscores disabled" )

-- controls
set_string( MENU_CAP_CONTROLS,            "Kontrole" )
set_string( MENU_CAP_2PCONTROLS,          "Kontrole-2 Igraca" )
set_string( MENU_CAP_SPCONTROLS,          "Special controls" )
set_string( MENU_TEXT_PLAYER1,            "Prvi Igrac" )
set_string( MENU_TEXT_PLAYER2,            "Drugi Igrac" )
set_string( CONTROL_LEFT,                 "Okret Ulijevo" )
set_string( CONTROL_RIGHT,                "Okret Udesno" )
set_string( CONTROL_THRUST,               "Mlaznice" )
set_string( CONTROL_SHOOT,                "Pucanje" )
set_string( CONTROL_NEXTWEAP,             "Sljedece Oruzje" )
set_string( CONTROL_PREVWEAP,             "Prethodno Oruzje" )
set_string( CONTROL_W1,                   "Oruzje 1" )
set_string( CONTROL_W2,                   "Oruzje 2" )
set_string( CONTROL_W3,                   "Oruzje 3" )
set_string( CONTROL_W4,                   "Oruzje 4" )
set_string( CONTROL_W5,                   "Oruzje 5" )
set_string( CONTROL_W6,                   "Oruzje 6" )
set_string( CONTROL_EXTRA_ACTION,         "Aktiviranje Dodatka" )
set_string( CONTROL_EXTRA2,               "Specijal" )
set_string( CONTROL_PAUSE,	          "Pause" )
set_string( CONTROL_SCREENSHOT,           "Screenshot" )
set_string( CONTROL_PANEL,                "Panel on/off" )
set_string( CONTROL_DEBUG,                "Debug messages" )
set_string( CONTROL_CHAT,                 "Chat" )

-- keyboard
set_string( KEY_LCONTROL,                 "Control Left" )
set_string( KEY_RCONTROL,                 "Control Right" )
set_string( KEY_ALT,                      "Alt Left" )
set_string( KEY_ALTGR,                    "Alt Gr" )
set_string( KEY_LSHIFT,                   "Shift Left" )
set_string( KEY_RSHIFT,                   "Shift Right" )
set_string( KEY_SPACE,                    "Space" )
set_string( KEY_LWIN,                     "Left Win" )
set_string( KEY_RWIN,                     "Right Win" )
set_string( KEY_MENU,                     "Win Menu" )
set_string( KEY_TAB,                      "TAB" )
set_string( KEY_ENTER,                    "Enter" )
set_string( KEY_BACKSPACE,                "Backspace" )
set_string( KEY_MINUS,                    "Minus" )
set_string( KEY_ESC,                      "Escape" )
set_string( KEY_TILDE,                    "Tilde ~")
set_string( KEY_EQUALS,                   "Equal Sign =" )
set_string( KEY_OPENBRACE,                "Open Brace" )
set_string( KEY_CLOSEBRACE,               "Close Brace" )
set_string( KEY_COLON,                    "Colon" )
set_string( KEY_QUOTE,                    "Quote" )
set_string( KEY_BACKSLASH,                "Backslash" )
set_string( KEY_BACKSLASH2,               "Backslash 2" )
set_string( KEY_COMMA,                    "Comma" )
set_string( KEY_STOP,                     "Stop" )
set_string( KEY_SLASH,                    "Slash" )
set_string( KEY_NUMLOCK,                  "Num Lock" )
set_string( KEY_CAPSLOCK,                 "Capslock" )
set_string( KEY_SCRLOCK,                  "Scroll Lock" )
set_string( KEY_F1,                       "F1" )
set_string( KEY_F2,                       "F2" )
set_string( KEY_F3,                       "F3" )
set_string( KEY_F4,                       "F4" )
set_string( KEY_F5,                       "F5" )
set_string( KEY_F6,                       "F6" )
set_string( KEY_F7,                       "F7" )
set_string( KEY_F8,                       "F8" )
set_string( KEY_F9,                       "F9" )
set_string( KEY_F10,                      "F10" )
set_string( KEY_F11,                      "F11" )
set_string( KEY_F12,                      "F12" )
set_string( KEY_PRTSCR,                   "Print Screen" )
set_string( KEY_PAUSE,                    "Pause" )
set_string( KEY_INSERT,                   "Insert" )
set_string( KEY_DEL,                      "Delete" )
set_string( KEY_HOME,                     "Home" )
set_string( KEY_END,                      "End" )
set_string( KEY_PGUP,                     "Page Up" )
set_string( KEY_PGDN,                     "Page Down" )
set_string( KEY_LEFT,                     "Arrow Left" )
set_string( KEY_RIGHT,                    "Arrow Right" )
set_string( KEY_UP,                       "Arrow Up" )
set_string( KEY_DOWN,                     "Arrow Down" )
set_string( KEY_SLASH_PAD,                "Slash [Pad]" )
set_string( KEY_0_PAD,                    "0 [Pad]" )
set_string( KEY_1_PAD,                    "1 [Pad]" )
set_string( KEY_2_PAD,                    "2 [Pad]" )
set_string( KEY_3_PAD,                    "3 [Pad]" )
set_string( KEY_4_PAD,                    "4 [Pad]" )
set_string( KEY_5_PAD,                    "5 [Pad]" )
set_string( KEY_6_PAD,                    "6 [Pad]" )
set_string( KEY_7_PAD,                    "7 [Pad]" )
set_string( KEY_8_PAD,                    "8 [Pad]" )
set_string( KEY_9_PAD,                    "9 [Pad]" )
set_string( KEY_ENTER_PAD,                "Enter [Pad]" )
set_string( KEY_PLUS_PAD,                 "Plus [Pad]" )
set_string( KEY_MINUS_PAD,                "Minus [Pad]" )
set_string( KEY_ASTERISK,                 "Asterisk" )
set_string( JOY0_UP,                      "Joy 1: Up" )
set_string( JOY0_DOWN,                    "Joy 1: Down" )
set_string( JOY0_LEFT,                    "Joy 1: Left" )
set_string( JOY0_RIGHT,                   "Joy 1: Right" )
set_string( JOY0_B1,                      "Joy 1: Button 1" )
set_string( JOY0_B2,                      "Joy 1: Button 2" )
set_string( JOY0_B3,                      "Joy 1: Button 3" )
set_string( JOY0_B4,                      "Joy 1: Button 4" )
set_string( JOY0_B5,                      "Joy 1: Button 5" )
set_string( JOY0_B6,                      "Joy 1: Button 6" )
set_string( JOY1_UP,                      "Joy 2: Up" )
set_string( JOY1_DOWN,                    "Joy 2: Down" )
set_string( JOY1_LEFT,                    "Joy 2: Left" )
set_string( JOY1_RIGHT,                   "Joy 2: Right" )
set_string( JOY1_B1,                      "Joy 2: Button 1" )
set_string( JOY1_B2,                      "Joy 2: Button 2" )
set_string( JOY1_B3,                      "Joy 2: Button 3" )
set_string( JOY1_B4,                      "Joy 2: Button 4" )
set_string( JOY1_B5,                      "Joy 2: Button 5" )
set_string( JOY1_B6,                      "Joy 2: Button 6" )

-- other/misc
set_string( MENU_YES,                     "Da" )
set_string( MENU_NO,                      "Ne" )
set_string( MENU_OK,                      "U Redu" )

-- ===========================================================


end
