/* Allegro datafile object indexes, produced by grabber v4.0.1, MSVC */
/* Datafile: d:\ANWEND\DJGPP\allegro\tools\gs.dat */
/* Date: Thu Jun 09 00:08:18 2005 */
/* Do not hand edit! */

#define arial14                          0        /* FONT */
#define arial14m                         1        /* FONT */
#define base_cargo                       2        /* RLE  */
#define base_cust_left                   3        /* RLE  */
#define base_cust_middle                 4        /* RLE  */
#define base_cust_right                  5        /* RLE  */
#define base_home                        6        /* RLE  */
#define base_lenemy                      7        /* RLE  */
#define base_reload_1                    8        /* RLE  */
#define base_reload_2                    9        /* RLE  */
#define base_senemy                      10       /* RLE  */
#define cargo1                           11       /* BMP  */
#define cargo_bigbombs1                  12       /* BMP  */
#define cargo_bigbombs3                  13       /* BMP  */
#define cargo_bombs10                    14       /* BMP  */
#define cargo_bombs20                    15       /* BMP  */
#define cargo_fuel                       16       /* BMP  */
#define cargo_life                       17       /* BMP  */
#define cargo_mgbullets                  18       /* BMP  */
#define cargo_mine1                      19       /* BMP  */
#define cargo_mine2                      20       /* BMP  */
#define cargo_mine3                      21       /* BMP  */
#define cargo_rockets                    22       /* BMP  */
#define cargo_shield                     23       /* BMP  */
#define debris_1_01                      24       /* BMP  */
#define debris_1_02                      25       /* BMP  */
#define debris_1_03                      26       /* BMP  */
#define debris_1_04                      27       /* BMP  */
#define debris_1_05                      28       /* BMP  */
#define debris_1_06                      29       /* BMP  */
#define debris_1_07                      30       /* BMP  */
#define debris_1_08                      31       /* BMP  */
#define debris_1_09                      32       /* BMP  */
#define debris_1_10                      33       /* BMP  */
#define debris_2_01                      34       /* BMP  */
#define debris_2_02                      35       /* BMP  */
#define debris_2_03                      36       /* BMP  */
#define debris_2_04                      37       /* BMP  */
#define debris_2_05                      38       /* BMP  */
#define debris_2_06                      39       /* BMP  */
#define debris_2_07                      40       /* BMP  */
#define debris_2_08                      41       /* BMP  */
#define debris_2_09                      42       /* BMP  */
#define debris_2_10                      43       /* BMP  */
#define debris_3_01                      44       /* BMP  */
#define debris_3_02                      45       /* BMP  */
#define debris_3_03                      46       /* BMP  */
#define debris_3_04                      47       /* BMP  */
#define debris_3_05                      48       /* BMP  */
#define debris_3_06                      49       /* BMP  */
#define debris_3_07                      50       /* BMP  */
#define debris_3_08                      51       /* BMP  */
#define debris_3_09                      52       /* BMP  */
#define debris_3_10                      53       /* BMP  */
#define debris_4_01                      54       /* BMP  */
#define debris_4_02                      55       /* BMP  */
#define debris_4_03                      56       /* BMP  */
#define debris_4_04                      57       /* BMP  */
#define debris_4_05                      58       /* BMP  */
#define debris_4_06                      59       /* BMP  */
#define debris_4_07                      60       /* BMP  */
#define debris_4_08                      61       /* BMP  */
#define debris_4_09                      62       /* BMP  */
#define debris_4_10                      63       /* BMP  */
#define debris_5_01                      64       /* BMP  */
#define debris_5_02                      65       /* BMP  */
#define debris_5_03                      66       /* BMP  */
#define debris_5_04                      67       /* BMP  */
#define debris_5_05                      68       /* BMP  */
#define debris_5_06                      69       /* BMP  */
#define debris_5_07                      70       /* BMP  */
#define debris_5_08                      71       /* BMP  */
#define debris_5_09                      72       /* BMP  */
#define debris_5_10                      73       /* BMP  */
#define effect_beam1_1                   74       /* RLE  */
#define effect_beam1_2                   75       /* RLE  */
#define effect_beam1_3                   76       /* RLE  */
#define effect_beam1_4                   77       /* RLE  */
#define effect_beam1_5                   78       /* RLE  */
#define effect_beam2_01                  79       /* RLE  */
#define effect_beam2_02                  80       /* RLE  */
#define effect_beam2_03                  81       /* RLE  */
#define effect_beam2_04                  82       /* RLE  */
#define effect_beam2_05                  83       /* RLE  */
#define effect_beam2_06                  84       /* RLE  */
#define effect_beam2_07                  85       /* RLE  */
#define effect_beam2_08                  86       /* RLE  */
#define effect_beam2_09                  87       /* RLE  */
#define effect_beam2_10                  88       /* RLE  */
#define effect_gravfield_1               89       /* RLE  */
#define effect_gravfield_2               90       /* RLE  */
#define effect_gravfield_3               91       /* RLE  */
#define effect_gravfield_4               92       /* RLE  */
#define effect_shield_1                  93       /* BMP  */
#define effect_shield_2                  94       /* BMP  */
#define effect_shield_3                  95       /* BMP  */
#define effect_shield_base_1             96       /* RLE  */
#define effect_shield_base_2             97       /* RLE  */
#define effect_shield_base_3             98       /* RLE  */
#define effect_tele2_01                  99       /* RLE  */
#define effect_tele2_02                  100      /* RLE  */
#define effect_tele2_03                  101      /* RLE  */
#define effect_tele2_04                  102      /* RLE  */
#define effect_tele2_05                  103      /* RLE  */
#define effect_tele2_06                  104      /* RLE  */
#define effect_tele2_07                  105      /* RLE  */
#define effect_tele2_08                  106      /* RLE  */
#define effect_tele2_09                  107      /* RLE  */
#define effect_tele2_10                  108      /* RLE  */
#define effect_tele_01                   109      /* RLE  */
#define effect_tele_02                   110      /* RLE  */
#define effect_tele_03                   111      /* RLE  */
#define effect_tele_04                   112      /* RLE  */
#define effect_tele_05                   113      /* RLE  */
#define effect_tele_06                   114      /* RLE  */
#define effect_tele_07                   115      /* RLE  */
#define effect_tele_08                   116      /* RLE  */
#define effect_tele_09                   117      /* RLE  */
#define effect_tele_10                   118      /* RLE  */
#define enemy_bigboss1_1                 119      /* RLE  */
#define enemy_bigboss1_2                 120      /* RLE  */
#define enemy_bigboss1_3                 121      /* RLE  */
#define enemy_bigboss1_4                 122      /* RLE  */
#define enemy_bigboss1_5                 123      /* RLE  */
#define enemy_n1_1                       124      /* RLE  */
#define enemy_n1_2                       125      /* RLE  */
#define enemy_n1_3                       126      /* RLE  */
#define enemy_n1_4                       127      /* RLE  */
#define enemy_n1_5                       128      /* RLE  */
#define enemy_s1_01                      129      /* RLE  */
#define enemy_s1_02                      130      /* RLE  */
#define enemy_s1_03                      131      /* RLE  */
#define enemy_s1_04                      132      /* RLE  */
#define enemy_s1_05                      133      /* RLE  */
#define enemy_s2_01                      134      /* RLE  */
#define enemy_s2_02                      135      /* RLE  */
#define enemy_s2_03                      136      /* RLE  */
#define enemy_s3_01                      137      /* RLE  */
#define enemy_s3_02                      138      /* RLE  */
#define enemy_s3_03                      139      /* RLE  */
#define enemy_s3_04                      140      /* RLE  */
#define enemy_s3_05                      141      /* RLE  */
#define enemy_s3_06                      142      /* RLE  */
#define enemy_s3_07                      143      /* RLE  */
#define enemy_s3_08                      144      /* RLE  */
#define enemy_s3_09                      145      /* RLE  */
#define enemy_s4_01                      146      /* RLE  */
#define enemy_s4_02                      147      /* RLE  */
#define enemy_s4_03                      148      /* RLE  */
#define enemy_s4_04                      149      /* RLE  */
#define enemy_s4_05                      150      /* RLE  */
#define enemy_s4_06                      151      /* RLE  */
#define enemy_s4_07                      152      /* RLE  */
#define enemy_s4_08                      153      /* RLE  */
#define enemy_s4_09                      154      /* RLE  */
#define enemy_s5_01                      155      /* RLE  */
#define enemy_s5_02                      156      /* RLE  */
#define enemy_s5_03                      157      /* RLE  */
#define enemy_s5_04                      158      /* RLE  */
#define enemy_s5_05                      159      /* RLE  */
#define enemy_s5_06                      160      /* RLE  */
#define enemy_s5_07                      161      /* RLE  */
#define enemy_s5_08                      162      /* RLE  */
#define enemy_tank1_01                   163      /* RLE  */
#define enemy_tank1_02                   164      /* RLE  */
#define enemy_tank1_03                   165      /* RLE  */
#define enemy_tank2_01                   166      /* RLE  */
#define enemy_tank2_02                   167      /* RLE  */
#define expl_big2_01                     168      /* RLE  */
#define expl_big2_02                     169      /* RLE  */
#define expl_big2_03                     170      /* RLE  */
#define expl_big2_04                     171      /* RLE  */
#define expl_big2_05                     172      /* RLE  */
#define expl_big2_06                     173      /* RLE  */
#define expl_big2_07                     174      /* RLE  */
#define expl_big2_08                     175      /* RLE  */
#define expl_big2_09                     176      /* RLE  */
#define expl_big2_10                     177      /* RLE  */
#define expl_big2_11                     178      /* RLE  */
#define expl_big2_12                     179      /* RLE  */
#define expl_big2_13                     180      /* RLE  */
#define expl_big2_14                     181      /* RLE  */
#define expl_big_1                       182      /* RLE  */
#define expl_big_2                       183      /* RLE  */
#define expl_big_3                       184      /* RLE  */
#define expl_big_4                       185      /* RLE  */
#define expl_big_5                       186      /* RLE  */
#define expl_med1_01                     187      /* RLE  */
#define expl_med1_02                     188      /* RLE  */
#define expl_med1_03                     189      /* RLE  */
#define expl_med1_04                     190      /* RLE  */
#define expl_med1_05                     191      /* RLE  */
#define expl_med1_06                     192      /* RLE  */
#define expl_med1_07                     193      /* RLE  */
#define expl_sm1_01                      194      /* RLE  */
#define expl_sm1_02                      195      /* RLE  */
#define expl_sm1_03                      196      /* RLE  */
#define expl_sm1_04                      197      /* RLE  */
#define expl_sm1_05                      198      /* RLE  */
#define expl_sm1_06                      199      /* RLE  */
#define expl_sm1_07                      200      /* RLE  */
#define expl_sm1_08                      201      /* RLE  */
#define expl_sm1_09                      202      /* RLE  */
#define expl_sm1_10                      203      /* RLE  */
#define expl_sm2_01                      204      /* RLE  */
#define expl_sm2_02                      205      /* RLE  */
#define expl_sm2_03                      206      /* RLE  */
#define expl_sm2_04                      207      /* RLE  */
#define expl_sm2_05                      208      /* RLE  */
#define expl_sm2_06                      209      /* RLE  */
#define expl_sm2_07                      210      /* RLE  */
#define expl_sm3_01                      211      /* RLE  */
#define expl_sm3_02                      212      /* RLE  */
#define expl_sm3_03                      213      /* RLE  */
#define expl_sm3_04                      214      /* RLE  */
#define expl_sm3_05                      215      /* RLE  */
#define expl_sm4_01                      216      /* RLE  */
#define expl_sm4_02                      217      /* RLE  */
#define expl_sm4_03                      218      /* RLE  */
#define expl_sm_1                        219      /* RLE  */
#define gamepal                          220      /* PAL  */
#define obj_b_grav_1                     221      /* RLE  */
#define obj_b_grav_2                     222      /* RLE  */
#define obj_b_grav_3                     223      /* RLE  */
#define obj_backtile1                    224      /* RLE  */
#define obj_backtile2                    225      /* RLE  */
#define obj_block1                       226      /* RLE  */
#define obj_block2                       227      /* RLE  */
#define obj_building1_1                  228      /* RLE  */
#define obj_building2_1                  229      /* RLE  */
#define obj_building3_1                  230      /* RLE  */
#define obj_building4_1                  231      /* RLE  */
#define obj_building4_2                  232      /* RLE  */
#define obj_bumpd_1                      233      /* RLE  */
#define obj_bumpd_2                      234      /* RLE  */
#define obj_bumpd_3                      235      /* RLE  */
#define obj_bumpl_1                      236      /* RLE  */
#define obj_bumpl_2                      237      /* RLE  */
#define obj_bumpl_3                      238      /* RLE  */
#define obj_bumpr_1                      239      /* RLE  */
#define obj_bumpr_2                      240      /* RLE  */
#define obj_bumpr_3                      241      /* RLE  */
#define obj_bumpu_1                      242      /* RLE  */
#define obj_bumpu_2                      243      /* RLE  */
#define obj_bumpu_3                      244      /* RLE  */
#define obj_doorh2_1                     245      /* RLE  */
#define obj_doorh2_2                     246      /* RLE  */
#define obj_doorh2_3                     247      /* RLE  */
#define obj_doorh2_4                     248      /* RLE  */
#define obj_doorh_1                      249      /* RLE  */
#define obj_doorh_2                      250      /* RLE  */
#define obj_doorh_3                      251      /* RLE  */
#define obj_doorh_4                      252      /* RLE  */
#define obj_doorv2_1                     253      /* RLE  */
#define obj_doorv2_2                     254      /* RLE  */
#define obj_doorv2_3                     255      /* RLE  */
#define obj_doorv2_4                     256      /* RLE  */
#define obj_doorv_1                      257      /* RLE  */
#define obj_doorv_2                      258      /* RLE  */
#define obj_doorv_3                      259      /* RLE  */
#define obj_doorv_4                      260      /* RLE  */
#define obj_extra1_1                     261      /* RLE  */
#define obj_extra1_2                     262      /* RLE  */
#define obj_extra1_3                     263      /* RLE  */
#define obj_flag1_1                      264      /* RLE  */
#define obj_flag1_2                      265      /* RLE  */
#define obj_flag1_3                      266      /* RLE  */
#define obj_flag1_4                      267      /* RLE  */
#define obj_flag1_5                      268      /* RLE  */
#define obj_flag2_1                      269      /* RLE  */
#define obj_flag2_2                      270      /* RLE  */
#define obj_flag2_3                      271      /* RLE  */
#define obj_flag2_4                      272      /* RLE  */
#define obj_flag2_5                      273      /* RLE  */
#define obj_flag3_1                      274      /* RLE  */
#define obj_flag3_2                      275      /* RLE  */
#define obj_flag3_3                      276      /* RLE  */
#define obj_flag3_4                      277      /* RLE  */
#define obj_flag3_5                      278      /* RLE  */
#define obj_flag4_1                      279      /* RLE  */
#define obj_flag4_2                      280      /* RLE  */
#define obj_flag4_3                      281      /* RLE  */
#define obj_flag4_4                      282      /* RLE  */
#define obj_flag4_5                      283      /* RLE  */
#define obj_flag5_1                      284      /* RLE  */
#define obj_flag5_2                      285      /* RLE  */
#define obj_flag5_3                      286      /* RLE  */
#define obj_flag5_4                      287      /* RLE  */
#define obj_flag5_5                      288      /* RLE  */
#define obj_flag6_1                      289      /* RLE  */
#define obj_flag6_2                      290      /* RLE  */
#define obj_flag6_3                      291      /* RLE  */
#define obj_flag6_4                      292      /* RLE  */
#define obj_flag6_5                      293      /* RLE  */
#define obj_gstone_b1                    294      /* RLE  */
#define obj_gstone_s1                    295      /* RLE  */
#define obj_gstone_s2                    296      /* RLE  */
#define obj_gwalld_1                     297      /* RLE  */
#define obj_gwalld_2                     298      /* RLE  */
#define obj_gwalld_3                     299      /* RLE  */
#define obj_gwalld_4                     300      /* RLE  */
#define obj_gwalll_1                     301      /* RLE  */
#define obj_gwalll_2                     302      /* RLE  */
#define obj_gwalll_3                     303      /* RLE  */
#define obj_gwalll_4                     304      /* RLE  */
#define obj_gwallr_1                     305      /* RLE  */
#define obj_gwallr_2                     306      /* RLE  */
#define obj_gwallr_3                     307      /* RLE  */
#define obj_gwallr_4                     308      /* RLE  */
#define obj_gwallu_1                     309      /* RLE  */
#define obj_gwallu_2                     310      /* RLE  */
#define obj_gwallu_3                     311      /* RLE  */
#define obj_gwallu_4                     312      /* RLE  */
#define obj_man1_1                       313      /* RLE  */
#define obj_man1_2                       314      /* RLE  */
#define obj_man1_3                       315      /* RLE  */
#define obj_man1_4                       316      /* RLE  */
#define obj_pool1_1                      317      /* RLE  */
#define obj_pool1_2                      318      /* RLE  */
#define obj_pool1_3                      319      /* RLE  */
#define obj_pool2_1                      320      /* RLE  */
#define obj_pool2_2                      321      /* RLE  */
#define obj_pool2_3                      322      /* RLE  */
#define obj_ppile1                       323      /* RLE  */
#define obj_ppile2                       324      /* RLE  */
#define obj_rpoled_1                     325      /* RLE  */
#define obj_rpoled_2                     326      /* RLE  */
#define obj_rpoled_3                     327      /* RLE  */
#define obj_rpoled_4                     328      /* RLE  */
#define obj_rpoled_5                     329      /* RLE  */
#define obj_rpoled_6                     330      /* RLE  */
#define obj_rpolel_1                     331      /* RLE  */
#define obj_rpolel_2                     332      /* RLE  */
#define obj_rpolel_3                     333      /* RLE  */
#define obj_rpolel_4                     334      /* RLE  */
#define obj_rpolel_5                     335      /* RLE  */
#define obj_rpolel_6                     336      /* RLE  */
#define obj_rpoler_1                     337      /* RLE  */
#define obj_rpoler_2                     338      /* RLE  */
#define obj_rpoler_3                     339      /* RLE  */
#define obj_rpoler_4                     340      /* RLE  */
#define obj_rpoler_5                     341      /* RLE  */
#define obj_rpoler_6                     342      /* RLE  */
#define obj_rpoleu_1                     343      /* RLE  */
#define obj_rpoleu_2                     344      /* RLE  */
#define obj_rpoleu_3                     345      /* RLE  */
#define obj_rpoleu_4                     346      /* RLE  */
#define obj_rpoleu_5                     347      /* RLE  */
#define obj_rpoleu_6                     348      /* RLE  */
#define obj_switchd_1                    349      /* RLE  */
#define obj_switchd_2                    350      /* RLE  */
#define obj_switchl_1                    351      /* RLE  */
#define obj_switchl_2                    352      /* RLE  */
#define obj_switchr_1                    353      /* RLE  */
#define obj_switchr_2                    354      /* RLE  */
#define obj_switchu_1                    355      /* RLE  */
#define obj_switchu_2                    356      /* RLE  */
#define obj_tree_1                       357      /* RLE  */
#define obj_tree_2                       358      /* RLE  */
#define obj_tunnel1_1                    359      /* RLE  */
#define obj_tunnel1_2                    360      /* RLE  */
#define obj_tunnel1_3                    361      /* RLE  */
#define obj_tunnel1_4                    362      /* RLE  */
#define obj_tunnel1_5                    363      /* RLE  */
#define panel                            364      /* FILE */

#define panel_cpl_lpanel                 0        /* BMP  */
#define panel_div                        1        /* BMP  */
#define panel_frag_line                  2        /* BMP  */
#define panel_frag_line_vert             3        /* BMP  */
#define panel_fuel_line                  4        /* BMP  */
#define panel_fuel_line_vert             5        /* BMP  */
#define panel_fuelfrag_empty             6        /* BMP  */
#define panel_fuelfrag_vert              7        /* BMP  */
#define panel_half                       8        /* BMP  */
#define panel_half_right                 9        /* BMP  */
#define panel_hull_l_1                   10       /* BMP  */
#define panel_hull_l_2                   11       /* BMP  */
#define panel_hull_l_3                   12       /* BMP  */
#define panel_hull_r_1                   13       /* BMP  */
#define panel_hull_r_2                   14       /* BMP  */
#define panel_hull_r_3                   15       /* BMP  */
#define panel_num_med_0                  16       /* BMP  */
#define panel_num_med_1                  17       /* BMP  */
#define panel_num_med_2                  18       /* BMP  */
#define panel_num_med_3                  19       /* BMP  */
#define panel_num_med_4                  20       /* BMP  */
#define panel_num_med_5                  21       /* BMP  */
#define panel_num_med_6                  22       /* BMP  */
#define panel_num_med_7                  23       /* BMP  */
#define panel_num_med_8                  24       /* BMP  */
#define panel_num_med_9                  25       /* BMP  */
#define panel_num_small_0                26       /* BMP  */
#define panel_num_small_1                27       /* BMP  */
#define panel_num_small_2                28       /* BMP  */
#define panel_num_small_3                29       /* BMP  */
#define panel_num_small_4                30       /* BMP  */
#define panel_num_small_5                31       /* BMP  */
#define panel_num_small_6                32       /* BMP  */
#define panel_num_small_7                33       /* BMP  */
#define panel_num_small_8                34       /* BMP  */
#define panel_num_small_9                35       /* BMP  */
#define panel_pic_acid                   36       /* BMP  */
#define panel_pic_bigbomb                37       /* BMP  */
#define panel_pic_bomb                   38       /* BMP  */
#define panel_pic_bumper                 39       /* BMP  */
#define panel_pic_double                 40       /* BMP  */
#define panel_pic_empty                  41       /* BMP  */
#define panel_pic_freezer                42       /* BMP  */
#define panel_pic_gas                    43       /* BMP  */
#define panel_pic_laser                  44       /* BMP  */
#define panel_pic_mine1                  45       /* BMP  */
#define panel_pic_mine2                  46       /* BMP  */
#define panel_pic_mine3                  47       /* BMP  */
#define panel_pic_probe                  48       /* BMP  */
#define panel_pic_rocket                 49       /* BMP  */
#define panel_pic_shotgun                50       /* BMP  */
#define panel_pic_shrinker               51       /* BMP  */
#define panel_pic_single                 52       /* BMP  */
#define panel_radar_empty                53       /* BMP  */
#define panel_radar_noise_1              54       /* BMP  */
#define panel_radar_noise_2              55       /* BMP  */
#define panel_radar_noise_3              56       /* BMP  */
#define panel_shield_1                   57       /* BMP  */
#define panel_shield_2                   58       /* BMP  */
#define panel_shield_3                   59       /* BMP  */
#define panel_shield_4                   60       /* BMP  */
#define panel_shield_5                   61       /* BMP  */
#define panel_shield_empty               62       /* BMP  */
#define panel_shield_exp_1               63       /* BMP  */
#define panel_shield_exp_2               64       /* BMP  */
#define panel_shield_exp_3               65       /* BMP  */
#define panel_shield_exp_4               66       /* BMP  */
#define panel_shield_exp_5               67       /* BMP  */
#define panel_shield_exp_6               68       /* BMP  */
#define panel_shield_exp_7               69       /* BMP  */
#define panel_shield_exp_8               70       /* BMP  */
#define panel_shield_exp_9               71       /* BMP  */
#define panel_statbar                    72       /* BMP  */
#define panel_statline_hull              73       /* BMP  */
#define panel_statline_shield            74       /* BMP  */
#define panel_weapon1_1                  75       /* BMP  */
#define panel_weapon1_2                  76       /* BMP  */
#define panel_weapon1_3                  77       /* BMP  */
#define panel_weapon2_1                  78       /* BMP  */
#define panel_weapon2_2                  79       /* BMP  */
#define panel_weapon2_3                  80       /* BMP  */
#define panel_weapon3_1                  81       /* BMP  */
#define panel_weapon3_2                  82       /* BMP  */
#define panel_weapon3_3                  83       /* BMP  */
#define panel_weapon4_1                  84       /* BMP  */
#define panel_weapon4_2                  85       /* BMP  */
#define panel_weapon4_3                  86       /* BMP  */
#define panel_weapon5_1                  87       /* BMP  */
#define panel_weapon5_2                  88       /* BMP  */
#define panel_weapon5_3                  89       /* BMP  */
#define panel_weapon6_1                  90       /* BMP  */
#define panel_weapon6_2                  91       /* BMP  */
#define panel_weapon6_3                  92       /* BMP  */
#define panel_weapon_empty               93       /* BMP  */
#define panel_wshield_1                  94       /* BMP  */
#define panel_wshield_2                  95       /* BMP  */
#define panel_wshield_3                  96       /* BMP  */
#define panel_wshield_4                  97       /* BMP  */
#define panel_wshield_5                  98       /* BMP  */
#define panel_COUNT                      99

#define pile1                            365      /* RLE  */
#define pile2                            366      /* RLE  */
#define shooter1_1                       367      /* RLE  */
#define shooter_down1                    368      /* RLE  */
#define shooter_down2                    369      /* RLE  */
#define shooter_down3                    370      /* RLE  */
#define shooter_flak_1                   371      /* RLE  */
#define shooter_flak_2                   372      /* RLE  */
#define shooter_flak_3                   373      /* RLE  */
#define shooter_left1                    374      /* RLE  */
#define shooter_left2                    375      /* RLE  */
#define shooter_left3                    376      /* RLE  */
#define shooter_pulse_1                  377      /* RLE  */
#define shooter_pulse_2                  378      /* RLE  */
#define shooter_pulse_3                  379      /* RLE  */
#define shooter_right1                   380      /* RLE  */
#define shooter_right2                   381      /* RLE  */
#define shooter_right3                   382      /* RLE  */
#define shooter_up1                      383      /* RLE  */
#define shooter_up2                      384      /* RLE  */
#define shooter_up3                      385      /* RLE  */
#define weapon_acid1                     386      /* BMP  */
#define weapon_acid2                     387      /* BMP  */
#define weapon_acid3                     388      /* BMP  */
#define weapon_bigbomb1                  389      /* BMP  */
#define weapon_bigbomb2                  390      /* BMP  */
#define weapon_bigbomb3                  391      /* BMP  */
#define weapon_bomb1                     392      /* BMP  */
#define weapon_bomb2                     393      /* BMP  */
#define weapon_bomb3                     394      /* BMP  */
#define weapon_bumper1                   395      /* BMP  */
#define weapon_bumper2                   396      /* BMP  */
#define weapon_bumper3                   397      /* BMP  */
#define weapon_laser1                    398      /* BMP  */
#define weapon_laser2                    399      /* BMP  */
#define weapon_laser3                    400      /* BMP  */
#define weapon_mine1_1                   401      /* BMP  */
#define weapon_mine1_2                   402      /* BMP  */
#define weapon_mine1_3                   403      /* BMP  */
#define weapon_mine2_1                   404      /* BMP  */
#define weapon_mine2_2                   405      /* BMP  */
#define weapon_mine2_3                   406      /* BMP  */
#define weapon_mine3_1                   407      /* BMP  */
#define weapon_mine3_2                   408      /* BMP  */
#define weapon_mine3_3                   409      /* BMP  */
#define weapon_probe1                    410      /* BMP  */
#define weapon_probe2                    411      /* BMP  */
#define weapon_probe3                    412      /* BMP  */
#define weapon_rocket1                   413      /* BMP  */
#define weapon_rocket2                   414      /* BMP  */
#define weapon_rocket3                   415      /* BMP  */

